### ISSUE TITLE
Slow and repeated PgAttribute query

### ISSUE THREAD

**Issue by gsmet** [impossibl/pgjdbc-ng#100]
Hi,

We have put into production our first app using pgjdbc-ng and we started to have in our logs slow queries like:
Oct 21 04:41:23 <host> postgres[28860]: [2-1] LOG:  duration: 57.894 ms  execute <unnamed>:  select    attrelid as "relationId", attname as "name", atttypid as "typeId", atttypmod as "typeModifier", attlen as "length",    attnum as "number", not attnotnull as "nullable", pg_catalog.pg_get_expr(ad.adbin,ad.adrelid) like '%nextval(%' as "autoIncrement",    attndims as "numberOfDimensions", atthasdef as "hasDefault", reltype as "relationTypeId"  from    pg_catalog.pg_attribute a  left join pg_catalog.pg_attrdef ad    on (a.attrelid = ad.adrelid and a.attnum = ad.adnum) left join pg_catalog.pg_class c   on (a.attrelid = c.oid) where    not a.attisdropped
Oct 21 04:41:53 <host> postgres[28872]: [2-1] LOG:  duration: 30.808 ms  execute <unnamed>:  select    attrelid as "relationId", attname as "name", atttypid as "typeId", atttypmod as "typeModifier", attlen as "length",    attnum as "number", not attnotnull as "nullable", pg_catalog.pg_get_expr(ad.adbin,ad.adrelid) like '%nextval(%' as "autoIncrement",    attndims as "numberOfDimensions", atthasdef as "hasDefault", reltype as "relationTypeId"  from    pg_catalog.pg_attribute a  left join pg_catalog.pg_attrdef ad    on (a.attrelid = ad.adrelid and a.attnum = ad.adnum) left join pg_catalog.pg_class c   on (a.attrelid = c.oid) where    not a.attisdropped

I'm wondering if it's something expected?

Thanks.
## 

Guillaume

**Comment by kdubb** [comment]
These are the type loading queries.  They are what enable the use of binary mode.  They are expected but they should be extremely fast.

**Comment by kdubb** [comment]
Also, these queries should only be happening 1 time, on connect.

**Comment by gsmet** [comment]
OK, they are not that fast but the connect part makes sense and that's why I see them appearing randomly during the day: it's probably when a new connection is needed for the pool.

Thanks for your feedback.

**Comment by kdubb** [comment]
Out of curiosity, do you have a large number of custom types defined?

**Comment by gsmet** [comment]
No, not at all. It's a standard PostgreSQL without any extension.

The plan of the query is the following:

```
                                                            QUERY PLAN                                                             
-----------------------------------------------------------------------------------------------------------------------------------
 Hash Left Join  (cost=238.66..517.27 rows=4806 width=126) (actual time=10.900..20.295 rows=4807 loops=1)
   Hash Cond: (a.attrelid = c.oid)
   ->  Hash Right Join  (cost=208.15..396.65 rows=4806 width=122) (actual time=9.888..13.093 rows=4807 loops=1)
         Hash Cond: ((ad.adrelid = a.attrelid) AND (ad.adnum = a.attnum))
         ->  Seq Scan on pg_attrdef ad  (cost=0.00..18.10 rows=810 width=38) (actual time=0.001..0.001 rows=0 loops=1)
         ->  Hash  (cost=136.06..136.06 rows=4806 width=86) (actual time=9.870..9.870 rows=4807 loops=1)
               Buckets: 1024  Batches: 1  Memory Usage: 569kB
               ->  Seq Scan on pg_attribute a  (cost=0.00..136.06 rows=4806 width=86) (actual time=0.012..4.323 rows=4807 loops=1)
                     Filter: (NOT attisdropped)
   ->  Hash  (cost=22.45..22.45 rows=645 width=8) (actual time=0.956..0.956 rows=645 loops=1)
         Buckets: 1024  Batches: 1  Memory Usage: 26kB
         ->  Seq Scan on pg_class c  (cost=0.00..22.45 rows=645 width=8) (actual time=0.009..0.450 rows=645 loops=1)
 Total runtime: 21.936 ms
```

The query returns 4800+ rows.

**Comment by Rom1kz** [comment]
i have the same problem
is there a way to disable these requests ?

**Comment by chobostar** [comment]
These queries stucks in lock queue during some ALTER TABLE with CONTRAINTS and VACUUM FULL of pg_catalog tables.
