### ISSUE TITLE
PostgreSQL 9.4 Beta 3 timezone test failure

### ISSUE THREAD

**Issue by brettwooldridge** [impossibl/pgjdbc-ng#106]
I'm not sure if this is a PostgreSQL 9.4 bug, or a pgjdbc-ng bug:

```
Failed tests:
  TimezoneTest.testTimezoneWithSeconds:742 expected:<-1577929192000> but was:<-1577929189000>
```

**Comment by kdubb** [comment]
Almost assuredly a unit test problem.  The same problem exists with the mainstream driver; which these unit tests were adopted from.

**Comment by brettwooldridge** [comment]
What should we do about it?  The code is:

```
SET TimeZone = 'Europe/Helsinki'
SELECT '1920-01-01'::timestamptz
```

We're asserting that `rs.getTimestamp(1).getTime()` should be `-1577929192000`.  However, my epoch calculator shows that to be `Dec 31 1919 22:20:08 GMT` and `Jan 01 1920 01:20:08 EEST` (Helsinki).  PostgreSQL 9.4 is returning `-1577929189000`, which my epoch calculator shows as `Dec 31 1919 22:20:11 GMT` and `Jan 01 1920 01:20:11 EEST` (which also seems incorrect).

Strangely, this test passes when I switch to PostgreSQL 9.3 instead of 9.4 Beta 3 (same computer).

**Comment by kdubb** [comment]
Honestly I haven't really looked into it much.  It only seems to surface on certain days of the year.

**Comment by gsmet** [comment]
See http://www.postgresql.org/message-id/11276.1413991497@sss.pgh.pa.us .

**Comment by brettwooldridge** [comment]
Good find, thanks.  I'll look at their commit.

**Comment by gsmet** [comment]
Commit is here: https://github.com/pgjdbc/pgjdbc/commit/4874f9a693a3bb1c2ddcbfcbc916b5ce0ce1b5f6

(I can prepare a PR but I think it's going to be longer to merge than applying the change yourself)
