### ISSUE TITLE
Errors from triggers are hard to catch

### ISSUE THREAD

**Issue by andreak** [impossibl/pgjdbc-ng#111]
Hi.

I noticed that errors raised from triggers propagate as `PGSQLSimpleException`, and don't hold any info about table or trigger-name causing the exception.

Is it possible to enhance the error-handling to provide details about what caused the exception raised by a trigger-violation?

**Comment by gsmet** [comment]
Hi @andreak ,

Could you provide a test case with a trigger which generates an error?

Once we have this test case, it will be easier to see if something can be done to improve this.

Thanks!

**Comment by andreak** [comment]
When time permits, yes:-)
Do you know if any information about trigger-name, src-table etc. is provided at the protocol-level?

**Comment by gsmet** [comment]
I remembered having seen posts from Pavel on the -hackers list a while ago about this sort of things.

Pavel included something in libpq for 9.3: http://www.postgresql.org/docs/9.3/static/libpq-exec.html#LIBPQ-PQRESULTERRORFIELD .

Looks like they have been included in the protocol too:
http://www.postgresql.org/docs/9.3/static/protocol-error-fields.html

But it was initially for constraints: I'm not sure triggers are concerned.

So, your unit test will be very welcome to see what we can get from the protocol :).

**Comment by andreak** [comment]
Here is a basic test:

```
@RunWith(JUnit4.class)
public class TriggerErrorInformationTest {
    private Connection conn;

    @Before
    public void before() throws Exception {
        conn = TestUtil.openDB();
        Statement stmt = conn.createStatement();
        stmt.execute("DROP TABLE IF EXISTS triggertest");
        stmt.execute("DROP function IF EXISTS triggertest_tf()");
        stmt.execute("CREATE TABLE triggertest(id integer)");
        stmt.execute("CREATE OR REPLACE function triggertest_tf() RETURNS TRIGGER AS $$" +
            "BEGIN\n" +
            "    if NEW.id > 10 THEN\n" +
            "        RAISE EXCEPTION 'ID must be less then 10';\n" +
            "    end if;\n" +
            "    RETURN NEW;\n" +
            "END;" +
            "$$  LANGUAGE plpgsql");
        stmt.execute("CREATE TRIGGER triggertest_t AFTER INSERT OR UPDATE ON triggertest\n" +
            "FOR EACH ROW EXECUTE PROCEDURE triggertest_tf()");
        stmt.close();
    }

    @After
    public void after() throws SQLException {
        Statement stmt = conn.createStatement();
        stmt.execute("DROP TABLE triggertest");
        stmt.execute("DROP function triggertest_tf()");
        stmt.close();
        TestUtil.closeDB(conn);
    }

    @Test
    public void testExceptionFromTrigger() throws SQLException {
        String sql = "INSERT INTO triggertest(id) VALUES(11)";
        PreparedStatement ps = conn.prepareStatement(sql);
        try {
            ps.executeQuery();
        } catch (SQLException sqlException) {
            String sqlstate = sqlException.getSQLState();
            Assert.assertTrue(String.format("sqlstate should start with 27 or 72, but is %s", sqlstate)
                , sqlstate.startsWith("27") || sqlstate.startsWith("72"));
        }
        ps.close();

    }

}
```

**Comment by kdubb** [comment]
I just checked this and it's not able to be done without a server change.  Postgres is only delivering extended error information (schema, table, etc) on check constraint failures.

**Comment by kdubb** [comment]
I am closing we can revisit if the server ever adds support for this.

**Comment by andreak** [comment]
Tom Lane made me take a closer look at how RAISE works, so it looks like we have all we need to provide nice errors in JDBC based on trigger-violations.
If I redefine the trigger-function to this:

``` sql
BEGIN
    if NEW.id IS NULL THEN
        RAISE EXCEPTION 'ID must not be NULL' USING ERRCODE = '23502', COLUMN = 'id', SCHEMA = TG_TABLE_SCHEMA, TABLE = TG_TABLE_NAME;
    end if;
    RETURN NEW;
END;
$$  LANGUAGE plpgsql;
```

Then `schema`, `table`, `sqlstate` and `column` are all nicely populated in the PGSQLSimpleException's details.

**Comment by kdubb** [comment]
Nice!!

Just FYI,  If you wanted to use the more specific PGSQLIntegrityConstraintViolationException just use an ERRCODE starting with '23'.

P.S.  We need to start looking at documenting this stuff, probably on the Wiki.

**Comment by andreak** [comment]
Yes. I didn't update my text in the comment above but setting the ERRCOE to 23502 makes the driver use PGSQLIntegrityConstraintViolationException and not PGSQLSimpleException, which is perfect.

I'm not sure this belongs in this driver's docs as it's certainly a feature of PG and how RAISE works. Having it documented somewhere in the driver's docs would however have helped me use RAISE correctly in the first place...
