### ISSUE TITLE
Notification listener not getting async events from other sessions

### ISSUE THREAD

**Issue by InfoSec812** [impossibl/pgjdbc-ng#113]
I am in the process of writing a Camel component which uses pgjdbc-ng to produce/consume async events from PostgreSQL... The code can be found at:

https://github.com/InfoSec812/pgevent

The problem that I am having is that when I use Camel to both send and receive the events using the same connection, everything works fine and I see the notification listener consume the event.. When I just fire up the consumer in Camel and connect using 'psql' on another terminal and send notifications from there, I see no events come through... Am I missing something???

**Comment by kdubb** [comment]
I confess to not having looked through your code, but I am pretty sure I know the solution ;)

The fix for this is a simple one... make a strong reference to the PGNotificationListener.  The driver keeps weak references to listeners.   I ran into the same issue while I was writing a test rig for this issue.

**Comment by kdubb** [comment]
I looked into your code.  The error isn't with weak/strong references or anything in pgjdbc-ng... it's with your code.

Your FORMAT1 regex (and I suspect all of them suffer the same issue) uses non-greedy name matching. Thus the name "testchannel" is matched as "t".  Executing "NOTIFY t" results in successful execution of your code.

Change your non-greedy section to greedy (e.g. \w+? >> \w+ ) and "NOTIFY testchannel" succeeds.

A couple points...
1. **PLEASE debug your code thoroughly before raising issues in another project.**  This was an obvious problem that I recognized immediately and you could have found without involving us.
2. You are not closing any connections or statements as you use them; which is required by JDBC spec.  This leaks connections and, thanks to our helpful log messages, will yell at you considerably as you use this code.
