### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by cowwoc** [impossibl/pgjdbc-ng#120]
1. http://impossibl.github.io/pgjdbc-ng/ links to http://impossibl.github.io/pgjdbc-ng/apidocs/0.3/index.html which is a broken link.
2. https://github.com/impossibl/pgjdbc-ng should provide more information about the properties. For example, there is no way of knowing what the "housekeeper" property does.
3. https://github.com/impossibl/pgjdbc-ng should list the fully-qualified Driver class alongside the DataSource class name.
4. Documentation should mention expected JDBC url format (this is buried in the source-code of ConnectionUtil.URL_PATTERN. Specifically, it should mention that `jdbc:pgsql:///database` is not supported (third slash is meant to denote localhost)  and `jdbc://pgsql://localhost/database/schema` is also not supported.

**Comment by jesperpedersen** [comment]
Version 0.5 has been released, and web site has been updated
