### ISSUE TITLE
PGDriver should invoke DriverManager.registerDriver() on class load

### ISSUE THREAD

**Issue by cowwoc** [impossibl/pgjdbc-ng#121]
JDBC drivers are required invoke DriverManager.registerDriver() at class load, but PGDriver only does this from its constructor. This is problematic for two reasons:
1. It violates the specification laid out by https://docs.oracle.com/javase/6/docs/api/java/sql/DriverManager.html
2. One specific example of how this breaks real-life code is QueryDSL's Maven plugin. The plugin invokes `Class.forName(jdbcDriver)` followed by `DriverManager.getConnection()`. The latter fails to find the driver because it never registered itself.

Please move registration from the constructor to a static init block.

**Comment by kdubb** [comment]
Already completed in commit 3850f96ed0a631892e7500629489870273f20c58

**Comment by cowwoc** [comment]
@kdubb Perfect. When is the next release to Maven Central?
