### ISSUE TITLE
RowId not guaranteed to not change

### ISSUE THREAD

**Issue by davecramer** [impossibl/pgjdbc-ng#122]
https://github.com/impossibl/pgjdbc-ng/blob/57e5a8a57e87126d10b64db1110c359ed07c8dc6/src/main/java/com/impossibl/postgres/jdbc/PGDatabaseMetaData.java#L1714

Outside a transaction a row can be moved out from under you if it is vacuumed

**Comment by kdubb** [comment]
I'm not sure this is linking to the right line.  Are you referring to getBestRowIdentifier?  This links to a comment in getVersionColumns (which talks about ctid being guaranteed to change).

**Comment by davecramer** [comment]
You are correct, I read it wrong. Although I would disagree, ctid may or
may not change depending on HOT.

Dave Cramer

**Comment by kdubb** [comment]
Although most of this code has been heavily edited to fit this drivers type system and format I can attest to it beginning it's life as a conglomeration of files in the mainstream driver...

Considering I have no idea who KJ is I searched in the mainstream driver....
https://github.com/pgjdbc/pgjdbc/blob/master/org/postgresql/jdbc2/AbstractJdbc2DatabaseMetaData.java#L3264 

It's the same comment and all.  So are you suggesting we should be returning no rows here?

**Comment by davecramer** [comment]
KJ is Kris Jurka.

No, CTID is as close as it gets.
I think the comment is wrong in both places.

It probably should read guaranteed not to change as xmin, xmax, cmin, cmax
certainly change.

Dave Cramer

**Comment by kdubb** [comment]
Just to be clear... you mean it is guaranteed to change correct?  That's what this is looking for "something" that will change no matter what.

**Comment by davecramer** [comment]
Well actually it may not change on an update if it is a HOT update, but it
will be unique

Dave Cramer

**Comment by kdubb** [comment]
Closing as I believe this is as _correct_ as possible for Postgres. Tidying up.
