### ISSUE TITLE
Allow disabling prepared statement cache with prepareThreshold=0

### ISSUE THREAD

**Issue by slorion** [impossibl/pgjdbc-ng#127]
Please consider making it possible to disable the prepared statement cache via the connection string parameter `?prepareThreshold=0`. This would allow pgjdbc-ng to work with PgBouncer in transaction pooling mode as explained here: http://engineering.clever-cloud.com/java/2013/05/27/pgjdbc-now-pgbouncer-compliant.html. Some more background: http://www.depesz.com/2012/12/02/what-is-the-point-of-bouncing/

**Comment by jesperpedersen** [comment]
Supported in version 0.5
