### ISSUE TITLE
BlobTest fails due to incorrect version check

### ISSUE THREAD

**Issue by jesperpedersen** [impossibl/pgjdbc-ng#13]
Using current master against PostgreSQL 9.2.4 fails the BlobTest, since LargeObject64 is chosen over LargeObject.

When looking at the compatible() compare, this.major is set to 9; this.minor + this.revision are 0, hence it passes.

The method should probably be cleaned up a bit in order to verify null instances on both sides. Also if this.X takes precedence over the parameter.

**Comment by kdubb** [comment]
Fixed in b49e37ef7d94f6a065d8cdcef282f7d799ddc2a9
