### ISSUE TITLE
How about a 0.5 release?

### ISSUE THREAD

**Issue by andreak** [impossibl/pgjdbc-ng#130]
The fixes in the parser to avoid SOE warrants it for me:-)

**Comment by kdubb** [comment]
It seems it's about time. I'd love to nail down a regular schedule for point releases but we are so busy with an impending launch it's been very hard.

**Comment by andreak** [comment]
Ping......

**Comment by trygvis** [comment]
+1

Is there anything I can help with to get a release out the door?

**Comment by Tostino** [comment]
Also interested in this.

**Comment by s17t** [comment]
+1

**Comment by kdubb** [comment]
Many apologies to all!

Our new company has been working up to releasing our new product and I have had no time to participate with pgjdbc-ng.

Fortunately the other participants have been making great enhancements!

@jesperpedersen or @brettwooldridge, if one or both of you gentlemen work to tag something as 0.5 I'm sure I can manage to download it, run the tests and bounce it to maven central.

**Comment by jesperpedersen** [comment]
@kdubb I can do it once I have my last work branch merged - hopefully this week or next.

In the mean time people should test our current 'develop' branch, and report any issues found

**Comment by kdubb** [comment]
Yes this is true about just testing 'develop'.

Our projects internally use maven for pgjdbc-ng.  Maybe that's the pain point in general for most.  I know I always sigh when I have to install stuff locally (or into our company wide maven repo) rather than just pull from central.

That being said...

```
git clone https://github.com/impossibl/pgjdbc-ng.git
cd pgjdbc-ng
maven install -DskipTests=true
```

Isn't that bad either

**Comment by dpratt** [comment]
I've been doing the same - I forked to our local Stash instance, did a slight patch to the POM so it'd publish to our Artifactory server, and I have our CI build and deploy whenever there's an update.

**Comment by jesperpedersen** [comment]
Released

**Comment by andreak** [comment]
Any idea when this will be available on Maven-central?

**Comment by kdubb** [comment]
A few hours.  I am building & uploading now.

**Comment by andreak** [comment]
Sweet, thanks!

**Comment by kdubb** [comment]
After a bit of arguing with maven release plugin... 0.5 has been deployed to central.

**Comment by andreak** [comment]
På torsdag 30. april 2015 kl. 10:17:39, skrev Kevin Wooten <
notifications@github.com mailto:notifications@github.com>: After a bit of 
arguing with maven release plugin... 0.5 has been deployed to central.

 Coolio!   -- Andreas Joseph Krogh CTO / Partner - Visena AS Mobile: +47 909 
56 963 andreas@visena.com mailto:andreas@visena.com www.visena.com 
https://www.visena.com  https://www.visena.com
