### ISSUE TITLE
broken inserting of interval from string

### ISSUE THREAD

**Issue by Redeeman** [impossibl/pgjdbc-ng#131]
It appears inserting intervals like this:
try( PreparedStatement ps = conn.prepareStatement( "INSERT INTO urls_loads (url_id, loadtime) VALUES(?, ?::interval)" ) ) {
    ps.setInt( 1, utm.id );
    long touse = diff/1000;
    ps.setString( 2, "'" + touse + " microseconds'" );
    ps.executeUpdate();
}

loadtime column is of type interval, and printing out touse using system.out.println gives something like:
'4647685 microseconds'

running query in psql: SELECT  '4647685 microseconds'::interval
works, and the jdbc-code shown above also works with the "original" postgres jdbc driver

Server used is 9.4, and what actually happens is that it just goes in as "00:00:00"

**Comment by kdubb** [comment]
This is a bug in that the `String` to interval conversion is not correct.

To be correct this also requires implementing ISO interval parsing/formatting along with the Postgres parsing/formatting

**Comment by kdubb** [comment]
Fixed in #441, note that clients must be passing string intervals in ISO 8601 format; unless they are relying on server parsing.
