### ISSUE TITLE
UDTs in batch insert

### ISSUE THREAD

**Issue by anandnalya** [impossibl/pgjdbc-ng#132]
Hi,

I'm trying to batch insert data using this version 0.4 of this driver. I'm able to insert records one at a time but when doing batch insert using the JDBC batch api, I'm getting the following exception:

> Exception in thread "main" java.lang.NullPointerException
>   at com.impossibl.postgres.jdbc.SQLTypeUtils.mapSetType(SQLTypeUtils.java:84)
>   at com.impossibl.postgres.jdbc.PGPreparedStatement.coerceParameters(PGPreparedStatement.java:216)
>   at com.impossibl.postgres.jdbc.PGPreparedStatement.addBatch(PGPreparedStatement.java:280)
>   at org.apache.commons.dbcp2.DelegatingPreparedStatement.addBatch(DelegatingPreparedStatement.java:207)
>   at org.apache.commons.dbcp2.DelegatingPreparedStatement.addBatch(DelegatingPreparedStatement.java:207)

Following is the code snippet I'm using:

``` scala
// set the connection and type maps
val conn = postgresDBStore.getConnection
val conf = if (conn.getTypeMap != null) conn.getTypeMap else new util.HashMap[String, Class[_]]()
conf.put("bin", classOf[Bin])
conn.setTypeMap(conf)

val s = conn.prepareStatement("insert into testbin(k,b) values (?,?)");
  for (x <- 1 to 10){
    s.setString(1, "a" + x)
    val bin = new com.cvent.analytics.Bin
    bin.c = 1
    bin.mn = Random.nextInt()
    bin.mx = Random.nextLong()
    bin.s = Random.nextLong()
    s.setObject(2, bin, Types.STRUCT);
    s.addBatch()
  }
  s.executeBatch()
```

Am I doing something wrong here? On debugging a bit, I found that when not using the batch API, excuteUpdate method call PGPreparedStatement#parseIfNeeded which has a PGPreparedStatement#copyNonNullTypes call which sets proper values in  PGPreparedStatement#parameterTypes.

**Comment by miere** [comment]
I'm using the 0.5 version and I'm facing the same problem as described by @anandnalya.
I've posted the bellow code that simulates the error I'm facing.

``` java
List<User> retrieveUsers(){
    List<User> users = new ArrayList<>();
    ResultSet result = executeQuery( "SELECT * FROM users" );
    while ( result.next() )
        users.add( createUser( result ) );
    return user;
}

ResultSet executeQuery( String sql ){
    PreparedStatement stmt = conn.prepareStatement( sql, ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY);
    return stmt.executeQuery();
}

User createUser( ResultSet result ){
    return new User(
        result.getLong( "id" ),
        result.getString( "name" ) );
}
```

``` console
java.lang.NullPointerException: null
    at com.impossibl.postgres.jdbc.PGPreparedStatement.copyNonNullTypes(PGPreparedStatement.java:415) ~[pgjdbc-ng-0.5-complete.jar:na]
    at com.impossibl.postgres.jdbc.PGPreparedStatement.parseIfNeeded(PGPreparedStatement.java:221) ~[pgjdbc-ng-0.5-complete.jar:na]
    at com.impossibl.postgres.jdbc.PGPreparedStatement.execute(PGPreparedStatement.java:256) ~[pgjdbc-ng-0.5-complete.jar:na]
    at com.impossibl.postgres.jdbc.PGPreparedStatement.executeQuery(PGPreparedStatement.java:277) ~[pgjdbc-ng-0.5-complete.jar:na]
    at com.impossibl.postgres.jdbc.PGPreparedStatement.executeQuery(PGPreparedStatement.java:92) ~[pgjdbc-ng-0.5-complete.jar:na]
    at com.zaxxer.hikari.proxy.PreparedStatementProxy.executeQuery(PreparedStatementProxy.java:52) ~[HikariCP-2.3.5.jar:na]
    at com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.executeQuery(PreparedStatementJavassistProxy.java) ~[HikariCP-2.3.5.jar:na]
```

**Comment by jesperpedersen** [comment]
The NPE is clearly wrong, but could you debug it a bit more ? The code should at least throw a SQLException

**Comment by miere** [comment]
@jesperpedersen thank you so much for your fast answer... But I kinda "solved" the problem.
Taking a closer look to the main methods of `PreparedStatement` I've noted that my ConnectionPool were prematurely closing my connection. Changing from C3P0 to Hikari solved the problem.

Once NPE isn't a meaningful enough, maybe pgjdbc-ng could throw a message that explicitly notify the developer that the connection was closed when situations like this happens.

Let me take this opportunity to congratulate the pgjdbc-ng team. This driver seems very nice and fast.

**Comment by jesperpedersen** [comment]
Indeed, a missing `checkClosed` - fixed in https://github.com/impossibl/pgjdbc-ng/commit/ddb653e0034d112e6199f93de5dd4c35600c05ec

Thanks for the report !
