### ISSUE TITLE
Create Connection Pool 

### ISSUE THREAD

**Issue by ousema2003** [impossibl/pgjdbc-ng#133]
I need create connection pool with max connection ...

which class can i use fo this : 
com.impossibl.postgres.jdbc.PGDataSource
or 
com.impossibl.postgres.jdbc.PGConnectionPoolDataSource

and how to set the max connection property 

....

knowing that i tried the both but i can't found method to set the pool size .

**Comment by brettwooldridge** [comment]
The PGConnectionPoolDataSource is meant to be used by an application container, not by a consumer directly.  It is not itself a connection pool.  You need a separate connection pool like HikariCP or Tomcat DBCP.

**Comment by ousema2003** [comment]
could you please send me an example how to combine : pgjdbc-ng with hikariCP

**Comment by ousema2003** [comment]
also i need locate hikaryCP jar file ..

**Comment by brettwooldridge** [comment]
See documentation on the [HikariCP](https://github.com/brettwooldridge/HikariCP) project page.

**Comment by ousema2003** [comment]
i get a look at HikariCP link / doc but canno't locate any java library or jar file ...

could you please help me ...
