### ISSUE TITLE
idle in transaction

### ISSUE THREAD

**Issue by kofemann** [impossibl/pgjdbc-ng#146]
I have tried to use pgjdbc-ng driver as it aims to be better than the original JDBC driver from postgres.

I can see in did 5-10% performance increase with  pgjdbc-ng  - it really re-uses prepared statements, which is clear visible in postgres log: only bind and execute, no parse.

Nevertheless,  application get stack after couple of minutes. In the postgres I can see a query which is has a state "idle in transaction". On every  run , I get an other query in this state.

Our application is highly concurrent (a NFS server, with namespace stored in postgres DB) and during testing I create and delete thousands of files.

Thanks,
  k.

**Comment by jesperpedersen** [comment]
Do you have a stack traces of the stuck threads ?
Do you have a test case that replicates this issue ?
Does the issue happen if PrepareStatement cache is disabled ?

**Comment by kofemann** [comment]
Here is the stacktrace:

03 Apr 2015 10:04:31 (System) [] Thread: OncRpcSvc Worker(20) [AD-](5) TIMED_WAITING
03 Apr 2015 10:04:31 (System) []     java.lang.Object.wait(Native Method)
03 Apr 2015 10:04:31 (System) []     com.impossibl.postgres.protocol.v30.CommandImpl.waitFor(CommandImpl.java:119)
03 Apr 2015 10:04:31 (System) []     com.impossibl.postgres.protocol.v30.QueryCommandImpl.execute(QueryCommandImpl.java:173)
03 Apr 2015 10:04:31 (System) []     com.impossibl.postgres.protocol.v30.ProtocolImpl.execute(ProtocolImpl.java:369)
03 Apr 2015 10:04:31 (System) []     com.impossibl.postgres.system.BasicContext.queryResults(BasicContext.java:437)
03 Apr 2015 10:04:31 (System) []     com.impossibl.postgres.system.BasicContext.queryFirstResultString(BasicContext.java:524)
03 Apr 2015 10:04:31 (System) []     com.impossibl.postgres.jdbc.PGConnectionImpl.executeForString(PGConnectionImpl.java:519)
03 Apr 2015 10:04:31 (System) []     com.impossibl.postgres.jdbc.PGConnectionImpl.isValid(PGConnectionImpl.java:641)
03 Apr 2015 10:04:31 (System) []     com.zaxxer.hikari.pool.HikariPool.isConnectionAlive(HikariPool.java:131)
03 Apr 2015 10:04:31 (System) []     com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:208)
03 Apr 2015 10:04:31 (System) []     com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:183)
03 Apr 2015 10:04:31 (System) []     com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:91)

I see in the code inconsistent synchronizations, and https://github.com/impossibl/pgjdbc-ng/pull/147 was an attempt to fix it.

I will try to come up with a  test case.

**Comment by jesperpedersen** [comment]
I have merged support for findbugs, so maybe

```
mvn clean install site
mvn findbugs:gui
```

can help you track it down, and develop a test case for it

**Comment by kdubb** [comment]
I believe this issue was fixed a quite a while ago.  Please feel free to retry with current head revision and re-open the issue if you still have trouble.
