### ISSUE TITLE
setAutoCommit(true) + setNetworkTimeout(n) causes hang on PostgreSQL shutdown

### ISSUE THREAD

**Issue by csdillard** [impossibl/pgjdbc-ng#148]
When network timeout is set to a positive value and auto commit is `false`, the network timeout never seems to get triggered.

A simple test case goes like this:  Make a new `PGDataSource`.  Set its timeout with `setNetworkTimeout(1000)` (for example).  Get a `Connection` from it and call its `setAutoCommit(false)`.  Then loop forever, doing `SELECT 1`, `commit()`, then sleep.  While it's looping, shut down PostgreSQL.

Expected behavior is that shortly after PostgreSQL shutdown, an exception would be thrown.  But it just hangs.

If you comment out the `setAutoCommit(false)` (and the `commit()`), then it works as expected.

This was tested against the 0.5-SNAPSHOT version that's current as of 2015 Apr 06 (at 12pm Central).  Full code of my test case:

``` java
package test;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import com.impossibl.postgres.jdbc.PGDataSource;

public class TimeoutFailureTest {
    public static void main(String[] args) throws Throwable {
        boolean BREAK_IT = true;
        PGDataSource dataSource = new PGDataSource();
        dataSource.setHost("localhost");
        dataSource.setDatabase("tester");
        dataSource.setUser("tester");
        dataSource.setPassword("password");
        dataSource.setPort(5432);
        dataSource.setApplicationName("Broken Connection Test");
        dataSource.setNetworkTimeout(1000);

        Connection connection = dataSource.getConnection();
        if (BREAK_IT)
            connection.setAutoCommit(false);

        while (true) {
            try (PreparedStatement ps = connection.prepareStatement("SELECT 1");
                    ResultSet rs = ps.executeQuery()) {
                rs.next();
            }
            if (BREAK_IT)
                connection.commit();
            System.out.println("query completed.  shut down postgresql now...");
            Thread.sleep(1000);
        }
    }
}
```

**Comment by jesperpedersen** [comment]
I have added a test case: https://github.com/impossibl/pgjdbc-ng/commit/9a7341a2ee8f6cc1b07fd7b2347fdfbae74c7eee that you can modify

**Comment by csdillard** [comment]
Thanks for adding that test case.  Unfortunately (for me), I can't make it break!

So far I can only get bad behavior when PostgreSQL is shut down entirely.  I don't know what this means yet, but I'm going to at least re-title this issue to reflect the difference.  (And I'm going to keep trying to make it break with a simple test case.)

Also: for the record, I'm testing against PostgreSQL 9.3.6 in Fedora 21 with OpenJDK 1.8.0_40, and shutting down PostgreSQL with the command `systemctl stop postgresql`.

**Comment by jesperpedersen** [comment]
Did the latest changes solve all your scenarios ?

**Comment by csdillard** [comment]
Yes, that fixed it!  Thanks!
