### ISSUE TITLE
Checkstyle setup for the project

### ISSUE THREAD

**Issue by jesperpedersen** [impossibl/pgjdbc-ng#15]
It would be nice to have checkstyle integrated into the project in order to have a consistent style, which would make it easier to contribute.

Especially if the TABs are replaced with SPACEs instead.

**Comment by kdubb** [comment]
I have replaced tabs with 2 spaces and cleaned up end-of-line whitespace, which is the way I had though it was.

I am open to checkstyle but  as I the setup seems to be so rigorous I gave up.  Maybe in the near future I'll finish adding it.

**Comment by jesperpedersen** [comment]
PR16 contains an initial patch

**Comment by jesperpedersen** [comment]
PR17 finishes the initial setup

**Comment by kdubb** [comment]
Thanks for all the work!  Would you consider this completed? Or are there other items you are implementing or would suggest?

**Comment by jesperpedersen** [comment]
Lets close this for now. We can always add extra checks along the way, e.g. we would need to enforce JavaDoc on the public API at some point.
