### ISSUE TITLE
hang on batch writable CTE upsert-ish

### ISSUE THREAD

**Issue by Redeeman** [impossibl/pgjdbc-ng#159]
Hello.

Attempting to do a batch operation with following query:
WITH
toensure (name, comment) AS (
    VALUES ( 'tedst', 'hesdfst' )
),
existing AS (
    SELECT id FROM datasource WHERE name IN(SELECT name FROM toensure)
),
inserted AS (
    INSERT INTO datasource (name, comment) SELECT \* FROM toensure WHERE NOT EXISTS(SELECT 1 FROM existing) RETURNING id
)
SELECT id FROM existing
UNION ALL
SELECT id FROM inserted

it hangs when running PreparedStatement.executeBatch().

the .addBatch() calls go through fine (thousands of them), but it just sits hanging on executeBatch(). monitoring via top on the server says postgresql is "idle in transaction".

attempting to do the same with the stock driver yields:
org.postgresql.util.PSQLException: A result was returned when none was expected.
    at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleResultRows(AbstractJdbc2Statement.java:2711)
    at org.postgresql.core.v3.QueryExecutorImpl$ErrorTrackingResultHandler.handleResultRows(QueryExecutorImpl.java:349)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1915)
    at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1180)
    at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1201)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:412)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2929)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.postgresql.ds.jdbc23.AbstractJdbc23PooledConnection$StatementHandler.invoke(AbstractJdbc23PooledConnection.java:453)
    at com.sun.proxy.$Proxy1.executeBatch(Unknown Source)

What i wanted to do was issue this query in batch, then read the resultsets out. This is probably not an "officially endorsed" thing at all, but it would be kinda nifty :)

**Comment by kdubb** [comment]
addBatch doesn't do much but add values to a list. So it makes sense that you don't see anything until executeBatch is executed.

**Comment by Redeeman** [comment]
perhaps i expressed myself unclear, executeBatch() hangs, and never actually finishes, while the postgres process sits at "idle in transaction"

edit: ah, yeah, i get you now :) you are right

**Comment by jesperpedersen** [comment]
Could you provide a thread dump of the hang ?

Similar issue reported in #146 but we need more information to get further, or a test case that reproduces the issue in our test suite

**Comment by Redeeman** [comment]
im now a little bit in doubt as to whether it actually hangs or not.

I have around 30ms roundtrip to the actual database server, and since my dataset is around 50k batches, if it does a roundtrip for each, it could explain why it would appear to "hang".

will my query actually be transmitting the data in "one go" to the server, or will it issue one roundtrip/query pr batch? because if that indeed is so, im thinking it might be the cause

**Comment by kdubb** [comment]
Yes for "roundtrip".  The addBatch/executeBatch conceptually does 1 bind + N executes with parameters.

In practice Java has no limitations on the types of arguments each member of the batch can have. Which means that we essentially have to "bind only when necessary". If you use the same exact types for parameters in each member of the batch, you'll get 1 bind + N executes.  This should provide a nice performance win.

In the end though, yes, you are sending N executes to the server.  In it's current incarnation it is not going to work as "send all batches" -> "receive all results".

So, after reading all this you might think that a PreparedStatement offers the same exact value in our driver; and you'd be correct ;)

**Comment by Redeeman** [comment]
all types were the same, all batches were in loop with exact types and such, and i did the add/executeBatch on the preparedstatement with the query.

But this would explain the results, i guess it was not hanging after all then :) Sorry to waste your time.

Wouldnt it be possible to send all the batches in 1 go though?

**Comment by kdubb** [comment]
@Redeeman That's not really how Postgres works.  Without changes to the server sending a giant bunch of binary batches won't work.

The original driver uses a different method.  It concatenates query text along with their parameters and send the batch.  So in your case you'd be sending 50k queries as one SQL statement + 50k batches of parameters.

Neither of these is an ideal solution. In the end I don't really know if 50k was the size that JDBC spec writers were thinking of when designing the API. My knowledge of servers out there make me think this API will be slow on most implementations; but I'm no expert.

COPY may be what you want.  Currently it's not supported in our driver but check out the original driver's COPY support and see if that fits your needs for such a large batch.

**Comment by kdubb** [comment]
@Redeeman To clarify about COPY.  You could COPY all your parameters to a temp table and execute a single query pretty easily and it would be way faster than either option the drivers can do currently.

@jesperpedersen @brettwooldridge Guys any thoughts on making our batch update work this way behind the scenes?

**Comment by Redeeman** [comment]
Thanks, though i opted for a more "crazy" solution.

the query remains almost the same, but instead of having fixed assigned values in the "toensure" CTE, i unnest several arrays that in total forms the complete rowset to put in :)

i expect it uses lots more ram, but I can live with that :)
