### ISSUE TITLE
Issue using 0.5-devel with JBoss Developer Studio (JBS) with JPA/Data Explorer

### ISSUE THREAD

**Issue by mistahmikey** [impossibl/pgjdbc-ng#161]
I am able to create a "connection" using your driver, but for some reason, upon connecting to the database, it will not pull down the Postgres catalog, so JBS cannot do any build-time JPA annotation validation.  When I use the driver from Postgres to make the connection, a "Catalog" folder appears under the connection folder, and it contains all the schemas, etc., and the JPA features in JBS are happy.  When I create a connection using the same general Postgres connection template, but instead point to the pgjdbc-ng driver (while also changing the url to be compatible with the driver), upon connection there is an empty "Schema" folder.  This prevents JBS from validating against any information about the database, so JPA annotation compilation errors result.

I do not see any error information when I use pgjdbc-ng to connect in JBS, so I have no idea why it would behave so differently.  Let me know if I am missing something, or if I can provide you with any additional information about this problem.

**Comment by jesperpedersen** [comment]
We need to know which JDBC methods are being called, and what SQL that is sent to the database to get closer to knowing what this is about.

You can do a similar test with the official driver, and then compare. That could give an idea.

Thanks

**Comment by mistahmikey** [comment]
Afraid I am not exactly sure how to capture the information you are requesting.  How do I see what SQL JBS is using to interact with the database?  Is there some sort of "spy"  monitor in postgres I can run?

**Comment by jesperpedersen** [comment]
Likely same setup as #162, so see my "spy" suggestion there

**Comment by kdubb** [comment]
I believe this to be working on the latest head of `develop`; although `strict-mode` might need to be disabled.
