### ISSUE TITLE
Support for JSONB type

### ISSUE THREAD

**Issue by vasily-kartashov** [impossibl/pgjdbc-ng#163]
Do you think you could add support for JSONB type on par with JSON?

**Comment by jesperpedersen** [comment]
Definitely, we should have support for JSONB.

The integration should be something that maps nicely into the javax.json API.

Feel free to submit a patch for it.

**Comment by davecramer** [comment]
I think the challenge here is that the internal representation of JSONB is
very unique to postgres.

Dave Cramer

**Comment by jesperpedersen** [comment]
I didn't say it was going to be easy :)

Fallback would be to use the functions internally to get it into a more agreeable shape...

**Comment by kdubb** [comment]
http://git.postgresql.org/gitweb/?p=postgresql.git;a=blob_plain;f=src/backend/utils/adt/jsonb.c;hb=REL9_4_STABLE

I use the PG C source as a guide when implementing binary types.  This code seems to indicate JSONB is just a string with a version number.  This seems insane since that's what JSON is.  I can't see how I'm wrong since pg_type confirms these are the linked functions. Anybody know differently?

**Comment by davecramer** [comment]
The source seems to suggest that there is no binary send and receive. Which
makes sense if the internal representation is not anybody's standard

Dave Cramer

**Comment by Namphibian** [comment]
Hi 

We just started moving a legacy application to PostgreSQL and the developer is a bit bleeding edge so he went and implemented and upgraded all JSON types to JSONB datatypes all over the place. Initially I thought the official JDBC driver would handle these datatypes transparently. After realizing that the driver is not that up to date I went and started implementing my own Custom types for Hibernate so I can read JSONB. There was no code change required between reading JSON and JSONB at least in the hibernate side of things. I will be sharing some of this code on GIT soon.  

It seems that the JSONB datatype is converted to a string on the standard driver at least as the following code worked for me when reading  JSONB column:

``` java
/*
        Example of JSONB data stored in the Miscellaneous column
        "{"BPAY Check digit": "0"}"
       This can be represented in Java as a Map<String,String>


*/


 @SuppressWarnings("unused")
    @Override
    public Object nullSafeGet(ResultSet resultSet, String[] names,
            SessionImplementor session, Object owner) 
        throws HibernateException, SQLException { 
        /*
                The following line of code returned the JSONB datatype as a normal  string
                 which I can prse with Jackson

        */
        String jsonString = resultSet.getString(names[0]);
        if( resultSet.wasNull() )
              return null;

        return getDataFromJSONString(jsonString);
    } 


 @Override
    protected TreeMap getDataFromJSONString(Object jsonValueString) 
    {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        String jsonString = (String)jsonValueString;
        try 
        {
            return (new ObjectMapper()).readValue(jsonString,TreeMap.class);
        } 
        catch (IOException ex) 
        {
            Logger.getLogger(MiscellaneousJSONType.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
            return null;
        }
    }
```

I am just going to test the writing parts of the code before I publish.

**Comment by davecramer** [comment]
Pretty sure there is no binary type being output for JSONB as it is
internal to the server.

Dave Cramer

**Comment by jirutka** [comment]
If there’s no binary type for JSONB, could be `jsonb` type added in the same way as old `json` type or CITEXT (#190)?

**Comment by kdubb** [comment]
Added in 8e82727a42b97ed3fb9ea9ac2cd21a2d2d14b679
