### ISSUE TITLE
UDTs mapping

### ISSUE THREAD

**Issue by romastar** [impossibl/pgjdbc-ng#184]
I have a question about UDTs mapping.

Is it possible to get support for searching mapped database objects to Java classes (Composite types, Domains etc) including namespaces? For example when I have few schemas in my database and I have possibility to add my UDTs with the same name in different namespaces I can't map this objects in my java code by String key. As result I can't find my mapped classes for serializing arrays.

At now search in typeMap includes only name: 

CompositeType -> getJavaType() : Class<?> type = (customizations != null) ? customizations.get(getName()) :
or 
SQLTypeUtils -> mapGetType() : Class<?> mappedType = typeMap.get(sourceType.getName());

I think is a big restriction.

If it possible please add searching mapped classes in typeMap with namespace in key.

P.S. Sorry for my english. I hope you can understand what I mean.

**Comment by jesperpedersen** [comment]
Maybe try and expand `StructTest` with your use-cases that we can discuss from

**Comment by romastar** [comment]
Hi Jesper.
I has created test for my case. How I can add it or send it to you?
Thank you for help.

**Comment by jesperpedersen** [comment]
@romastar Please, send your changes as a pull request

**Comment by kdubb** [comment]
Fixed in #268
