### ISSUE TITLE
Version-conflict when including driver in war-file

### ISSUE THREAD

**Issue by andreak** [impossibl/pgjdbc-ng#192]
Hi all.

When trying to wrap a war-file with the pgjdbc-ng-0.5-complete.jar in WEB-INF/lib I get this at runtime when Tomcat starts:

```
Exception in thread "PG-JDBC EventLoop (3)" java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
```

I suspect this is due to the fact that we use Akka and it requires Netty-3.8.x

To avoid this I place pgjdbc-ng-0.5-complete.jar in $TOMCAT_HOME/lib which works correctly.

Is there any reason Netty (and other deps of this project) cannot be shaded to avoid version-conflicts?

Thanks.

**Comment by kdubb** [comment]
The `-complete` versions of the driver included shaded Netty.
