### ISSUE TITLE
about jsonb[]

### ISSUE THREAD

**Issue by springCat** [impossibl/pgjdbc-ng#197]
when i use the type jsonb[] , call the method getArray() in PGArray, the type of element in array would be the String ,but it is not the correct data,.it seems the type of element in Array is Object and it call the toString(),so the result would like this: [[Ljava.lang.Object;@3ad2e17,[Ljava.lang.Object;@8c3619e]

**Comment by kdubb** [comment]
Fixed in 8e82727a42b97ed3fb9ea9ac2cd21a2d2d14b679
