### ISSUE TITLE
Housekeeper configuration

### ISSUE THREAD

**Issue by jesperpedersen** [impossibl/pgjdbc-ng#20]
The housekeeper should be configured using a parameter in the connection url, such it can be enabled or disabled on a case-by-case basis.

Furthermore, it shouldn't be static, since that shares it across all deployments.

Alternative, configuration through a system property - default is disabled.

**Comment by kdubb** [comment]
It is implemented by way of a connection level parameter "housekeeper.enabled"; it defaults to being enabled.  Housekeeper is now an interface with a real and null implementation.  The setting is tested and the proper implementation is chosen in the PGDriver and passed into the PGConnection.  This organization should allow Datasources to choose a different default or make a new housekeeping scheme altogether.
