### ISSUE TITLE
pgjdbc-ng 0.6

### ISSUE THREAD

**Issue by jesperpedersen** [impossibl/pgjdbc-ng#203]
Release version 0.6 of the driver

**Comment by brcolow** [comment]
What is blocking this?

**Comment by kdubb** [comment]
Nothing but my time. I will get it done this weekend.

**Comment by brcolow** [comment]
Not a problem, thanks so much for your hard work.

**Comment by kdubb** [comment]
Released and sync'd to maven central

**Comment by jesperpedersen** [comment]
Thanks Kevin !

Web site updated
