### ISSUE TITLE
Wrong results when using getTime/getTimestamp

### ISSUE THREAD

**Issue by vlsi** [impossibl/pgjdbc-ng#206]
I've ran `TimezoneTest` from pgjdbc and there are lots of failures.
Test code is here: https://github.com/pgjdbc/pgjdbc/pull/387/files#diff-3c7c6e6379cec503322d6c309d14b3bdR8

Failures (8 of 16 test failed):

1)
getTimestamp fails when it consumes `time with time zone`:

```
Expected :-43200000
Actual   :43200000
rs.getTimestamp(4, cGMT13), the data is '15:00:00 +0300'
```

2) getTime fails in lots of cases: it both produces wrong time and wrong date (the date should always be 1970-01-01).

TimezoneTest.testLocalTimestampsInAtlanticAzores:

```
junit.framework.ComparisonFailure: getTime: 2015-09-03 12:00:00, timeZone: Atlantic/Azores 
Expected :1970-01-01 12:00:00
Actual   :1970-01-01 11:00:00
```

TimezoneTest.testLocalTimestampsInPacificApia:

```
junit.framework.ComparisonFailure: getTime: 2015-09-03 12:00:00, timeZone: Pacific/Apia 
Expected :1970-01-01 12:00:00
Actual   :1969-12-31 12:00:00
```

TimezoneTest.testLocalTimestampsInPacificNiue:

```
junit.framework.ComparisonFailure: getTime: 2015-09-03 12:00:00, timeZone: Pacific/Niue 
Expected :1970-01-01 12:00:00
Actual   :1970-01-01 11:30:00
```

TimezoneTest.testLocalTimestampsInAmericaAdak:

```
junit.framework.ComparisonFailure: getTime: 2015-09-03 12:00:00, transfer format: text, timeZone: America/Adak 
Expected :1970-01-01 12:00:00
Actual   :1970-01-01 10:00:00
```

TimezoneTest.testGetTime(TimezoneTest.java:311). The error message is not that obvious, however, the key point is pgjdbc-ng produced 1970-01-02 for `getTime(int, GMT+13)` call.

```
Expected :-43200000
Actual   :43200000

DB contains "15:00:00+03" in time with time zone column
testing rs.getTime(4, cGMT13)
```

etc

**Comment by kdubb** [comment]
Fixed in #349... tested with current (as of the time of this comment) Time, Date & Timestamp tests from both pgjdbc & pgjdbc-ng.
