### ISSUE TITLE
DataSource and XADataSource support

### ISSUE THREAD

**Issue by jesperpedersen** [impossibl/pgjdbc-ng#21]
Add support for the DataSource and XADataSource interfaces.

**Comment by jesperpedersen** [comment]
I have begone this task, will update once there is a WIP branch

**Comment by brettwooldridge** [comment]
Is this actively being worked?  I am willing to implement this.

**Comment by jesperpedersen** [comment]
Yes, making some changes as compared to the original driver, so it takes a bit longer. Expect preview in beginning of December

**Comment by jesperpedersen** [comment]
WIP - https://github.com/jesperpedersen/pgjdbc-ng/tree/ds

The branch will be rebased, and squashed during development. However, testing can begin.

**Comment by kdubb** [comment]
This is great!!  With this we are feature complete with JDBC 4.1 (unless I am missing something from the spec).

Any thoughts on how long until we can merge with develop? I have a couple things I want to start and not sure if I should wait or not.

**Comment by jesperpedersen** [comment]
Give me this week to finish up. Otherwise we can merge on Friday and finish up on develop. I think we are close.

Just push ahead, I'll rebase this branch with develop :)

**Comment by kdubb** [comment]
FYI, Netty has a Base64 class already.  Instead of adding our own.

Guess I could have commented the commit instead

**Comment by adamjgray** [comment]
What is the minimum java version for this project?  Is DatatypeConverter not sufficient for the base64 encoding and decoding?

**Comment by kdubb** [comment]
Good point.  We are squarely in Java 7 land... no plans on going backwards.

**Comment by adamjgray** [comment]
Also, back in January a coworker and I were in a ... bind with glassfish and had to overhaul the xa data source implementation from the original driver including a stab at implementing interleaving.  Our commits can be found in our fork of pgjdbc [here ](https://github.com/polarislabs/pgjdbc/tree/POLARIS_XA).  We ran against this version of the driver in glassfish for several months before we switched to jboss.

Full disclosure: After switching to JBoss, it was found that our implementation of of the xa datasource with interleaving wasn't as fast as jboss ignoring interleaving entirely; so we aren't actively using that driver anymore.  But it may turn out to be a decent resource here.  We also had started adding a set of XA tests in that codebase as well, though most of them target testing interleaving.

In any case, thanks for the work you guys are putting in.  @kdubb I know you were initially talking to my coworker about some of this as well.  I know we'd both be interesting in helping out once we're able to find the time.  I've been watching progress here as well hoping that I'll be able to contribute in some fashion or another.

**Comment by jesperpedersen** [comment]
@adamjgray I'll look at that - it was a quick port of the existing code. And "JBoss" doesn't ignore interleaving - trust me ;) Once the current PR is merged, just submit a PR with your work, and we can take it from there

**Comment by adamjgray** [comment]
It does if you tell it to 8 ).  I just meant that our currently implementation of interleaving is slower than not doing it at all.  But, it's always possible that we'd just need some performance tuning.  Once this PR is merged in, I'll start to take a look at what sort of combinations can be done.  Might be a good Christmas project.

**Comment by kdubb** [comment]
@adamjgray  I was under the impression Bryan and your's work had been accepted and mainlined.

Hopefully, we will be more responsive to PR's and accepting of new work ;)

**Comment by jesperpedersen** [comment]
@adamjgray You don't have to tell me - I wrote it ;) Looking forward to your contributions !

**Comment by jesperpedersen** [comment]
@kdubb Using another Base64 implementation is a separate concern that getting this PR merged. The main issue is that we have to be sure that the encoded string is on one line for all Xids. So, punting to later PR

**Comment by brettwooldridge** [comment]
Just wanted to report that so far my testing of the XADataSource has gone fairly well.  Initially I was seeing some issues, but I was running on a pre-release of Bitronix 3.0.  After upgrading (to a newer pre-release) those issues seemed to have been resolved.  There were a few issues, reported as bugs here, that seemingly will be resolved by the move to Netty 4.  I will continue testing with various configurations, and report any issues I find.

**Comment by jesperpedersen** [comment]
PR49

**Comment by jesperpedersen** [comment]
Merged
