### ISSUE TITLE
URL_PATTERN doesn't take _ in the hostname

### ISSUE THREAD

**Issue by abhishekparwal** [impossibl/pgjdbc-ng#212]
I had a hostname abc_xyz.corp.company.com and it is failing in _ in hostname.
Matcher urlMatcher = URL_PATTERN.matcher(url); of com.impossibl.postgres.jdbc.ConnectionUtil class.

Please fix it.

**Comment by dstipp** [comment]
Your hostnames are not valid.

Per RFC952:

> A "name" (Net, Host, Gateway, or Domain name) is a text string up to 24 characters drawn from the alphabet (A-Z), digits (0-9), minus sign (-), and period (.). Note that periods are only allowed when they serve to delimit components of "domain style names".

This was amended in RFC1123:

> the restriction on the first character is relaxed to allow either a letter or a digit.

More info from random IBM documentation:

> Avoid using the underscore (_) character in machine names. Internet standards dictate that domain names conform to the host name requirements described in Internet Official Protocol Standards RFC 952 and RFC 1123. Domain names must contain only letters (upper or lower case) and digits. Domain names can also contain dash characters ( - ) as long as the dashes are not on the ends of the name. Underscore characters ( _ ) are not supported in the host name

**Comment by kdubb** [comment]
So as far as I remember... 
Hostnames = Underscores NOT allowed
Domain Names = Underscores allowed

Is the hostname part of a URL an underscore or hostname... Not sure.  Google search just seemed to confuse me.
