### ISSUE TITLE
Failing unit test? testRaiseNotice(com.impossibl.postgres.jdbc.CallableStatementTest)

### ISSUE THREAD

**Issue by dstipp** [impossibl/pgjdbc-ng#215]
Is anyone else seeing this failure?

```
testRaiseNotice(com.impossibl.postgres.jdbc.CallableStatementTest)  Time elapsed: 0.05 sec  <<< FAILURE!
java.lang.AssertionError: null
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertNotNull(Assert.java:621)
    at org.junit.Assert.assertNotNull(Assert.java:631)
    at com.impossibl.postgres.jdbc.CallableStatementTest.testRaiseNotice(CallableStatementTest.java:307)
```

I appear to get it on JDK 7 & 8 on PostgreSQL 9.1, 9.2, 9.3, 9.4 and wanted to check if this was isolated to my setup or if others see this as well.  (Found in the Travis CI builds running 'mvn -e test' against 441b120)

**Comment by kdubb** [comment]
This might be travis related.  Locally this doesn't fail; for myself at least.

**Comment by dstipp** [comment]
Hm.  I got sidetracked from things here, hopefully can take a look again.  First step was getting the same set of test results from when I ran locally (local IDE, remote DB) vs running in travis...

**Comment by kdubb** [comment]
This was fixed via a little postgres session config magic. I checked it in earlier.
