### ISSUE TITLE
enum type not getting written from pgjdbc-ng

### ISSUE THREAD

**Issue by abhishekparwal** [impossibl/pgjdbc-ng#218]
I have state column which is of type enum (CREATE TYPE account_holder_state AS ENUM ('ACTIVE', 'SUSPEND', 'DEACTIVATE') ) .

When I try to do a insert it is allowed , but on updates gives a exception. Basically it is expecting state column of type account_holder_state but it is being set as text. Shouldn't the enum be allowed as text in pgjdbc-ng driver?

```
update
    public.account_holder 
set
    state=? 
where
    id=?
```

com.impossibl.postgres.jdbc.PGSQLSimpleException: column "state" is of type account_holder_state but expression is of type text
    at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:159) ~[pgjdbc-ng-0.5.jar:na]
    at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:136) ~[pgjdbc-ng-0.5.jar:na]
    at com.impossibl.postgres.jdbc.PGConnectionImpl.execute(PGConnectionImpl.java:438) ~[pgjdbc-ng-0.5.jar:na]
    at com.impossibl.postgres.jdbc.PGPreparedStatement.executeBatch(PGPreparedStatement.java:346) ~[pgjdbc-ng-0.5.jar:na]

**Comment by kdubb** [comment]
Can you provide a sample program that demonstrates the issue? I think I understand the issue but samples always speed things along.

**Comment by abhishekparwal** [comment]
Even i have to write it out the native code , as I am using jpa-hibernate which is generating this sql. Let me know if you want jpa code.

**Comment by abhishekparwal** [comment]
@kdubb  any updates?

**Comment by kdubb** [comment]
I need to look into this more in depth but as a workaround you should be able to use `state = ?:: account_holder_state` with no issues

**Comment by kdubb** [comment]
I added a unit test in PR #269.  It appears to work properly.  Can you check this with the head revision?
