### ISSUE TITLE
Move checkstyle verification to a dedicated travis job

### ISSUE THREAD

**Issue by vlsi** [impossibl/pgjdbc-ng#222]
Currently checkstyle is executed for each and every job, thus it disables running tests even if a single checkstyle violation was found.
Having checkstyle for each and every job makes the build longer and utilizes excessive Travis resources.

See https://github.com/impossibl/pgjdbc-ng/pull/221, https://travis-ci.org/impossibl/pgjdbc-ng/builds/99316327

**Comment by kdubb** [comment]
I'm no travis pro... thus I'll need to research how to actually do this.

**Comment by vlsi** [comment]
Neither am I.

There are two workable solutions:
1) Enumerate test matrix manually. Even though it looks ugly, it allows you to have completely unrelated steps.
Look here: https://github.com/pgjdbc/pgjdbc/blob/master/.travis.yml#L38-L43
It produces this job: https://travis-ci.org/pgjdbc/pgjdbc/builds/99278679. Note how `checkstyle` step is red, while all the other are green.

2) Put `if-else bash` logic. For instance `if (pg_version=9.1 and java=1.7) { additionally check style }`. However that would be more surprising in terms of "oh, we somehow failed pg 9.1 support" vs "checkstyle went wrong"

**Comment by kdubb** [comment]
Does that enumerated matrix also mean we can use the "faster container format"? Looks like pgjdbc uses that while ours is using the old method with sudo required.

**Comment by kdubb** [comment]
@vlsi I think I'll probably be stealing your travis.yml or at least parts of it :+1: You clearly know more about this than myself.

**Comment by vlsi** [comment]
@kdubb , be careful. There's https://github.com/pgjdbc/pgjdbc/issues/461 on "moving away from container format".

I'm not sure what is the best way to go, but "faster container format" is too tight for proper JDBC driver testing.

**Comment by kdubb** [comment]
Thanks, that's good info to know.

**Comment by kdubb** [comment]
Done and more in 0f2608253305c1f3bf628dc33492bb82a8eb3eb2
