### ISSUE TITLE
Travis setup needs max_prepared_transactions

### ISSUE THREAD

**Issue by jesperpedersen** [impossibl/pgjdbc-ng#226]
In order for the XA test cases to pass the Travis setup needs to have `max_prepared_transactions` set to a non-zero value

@kdubb Ideas ?

**Comment by jesperpedersen** [comment]
Blocking #225

**Comment by kdubb** [comment]
First guess would be to add this to travis.yml

```
before_script:
  - export PGDATA = $(psql -c "SHOW data_directory" -F "" -A -t -U postgres)
  - echo "max_prepared_transactions = 10" >> "$PGDATA/postgresql.conf"
  - pg_ctl restart
```

**Comment by kdubb** [comment]
Should probably put those commands in a single script and reference from travis.yml instead

**Comment by kdubb** [comment]
Apologies for the many replies but I was doing this a bit off the top of my head... those commands can clearly be added to `.travis/travis-install-dependencies` which is where all the current postgres setup is happening.

**Comment by jesperpedersen** [comment]
It is likely better to just use org.junit.Assume.assumeTrue(). Otherwise everybody would have to enable max_prepared_transactions.

So, I went that route.
