### ISSUE TITLE
Is "travis-install-dependencies" license clear?

### ISSUE THREAD

**Issue by vlsi** [impossibl/pgjdbc-ng#228]
The comment in https://github.com/impossibl/pgjdbc-ng/blob/develop/.travis/travis-install-dependencies#L3 leads to https://github.com/ckan/ckan/blob/master/bin/travis-install-dependencies which is AGPL. Is it compatible with BSD-like license of pgjdbc-ng?

I just came across the comment.

**Comment by kdubb** [comment]
The question is, what is the license of that file.  Is it really under AGPL? Only the authors can tell us. It may be and as such I guess we'll have to rewrite the same file; although it would probably look essentially identical.

Good catch, I didn't think to check up on this while committing.

**Comment by kdubb** [comment]
@vitorbaptista It appears you are the original author of the file referenced above. I accepted a commit using a modified version of that file without realizing it as such.  Since it has no license/copyright header should we assume it's an AGPL file (and thus incompatible with our BSD style license)?

**Comment by vitorbaptista** [comment]
@kdubb If it were up to me, I'd be happy to license that to you under BSD, MIT, or whatever you prefer. Unfortunately, as that code was done for the [Open Knowledge](http://okfn.org), I can't. I'm not sure when you took that file from CKAN, so I might not be the only author then.

That being the case, that file is AGPL. You can either try and get an authorization from Open Knowledge itself, or rewrite it. Given that the code is trivial, I think rewriting will be much quicker.

**Comment by jesperpedersen** [comment]
I think a rewrite is better. We don't need 8.4 - 9.0 f.ex.

@vlsi has made some improvements to the pgjdbc setup for XA, which could be included if he wants to release those

**Comment by vlsi** [comment]
Those are on guard of pgjdbc's code: https://github.com/pgjdbc/pgjdbc/commit/8c9898af9d6ab21f2a727cc2f673519d2c4352c7

Feel free to borrow that, however it is MIT-based, thus remember to keep the reference to the original author: https://github.com/pgjdbc/pgjdbc/commit/8c9898af9d6ab21f2a727cc2f673519d2c4352c7#diff-2ab7c8e6097b7237cf098448475bd6efR2

PS. It would be nice to implement SSL & domain socket configuration as well.

JFYI: I find `dist: trusty` to be faster to start and it seems to perform better.

**Comment by kdubb** [comment]
File was removed
