### ISSUE TITLE
ratpack.io Serivce, Hikari, NotifcationListene and connection hanging

### ISSUE THREAD

**Issue by mlusetti** [impossibl/pgjdbc-ng#232]
I use ratpack.io with Hikari connection pool and pgjdbc-ng.

During application bootstrap I'm using the NotificationListener facility to get postgresql notification, and It seems to work correctly, If I keep a strong reference in to the NotificationListener it works reliably.

The problem is that I would like to get another connection from Hikari (ratpack configured) connection pool to do some queries based on the content of the notification.

My issue is somehow relative to #162 as I understand it but different.

Here is the ratpack forum thread: https://forum.ratpack.io/Accessing-Hikari-connection-from-ratpack-server-Service-with-pgjdbc-ng-td1408.html

Could this possible due to the fact that the notification comes from a different EventLoop thread then the one defined within ratpack/hikari ? In the log I see:
[PG-JDBC EventLoop (1)] INFO  i.d.c.p.m.s.PushNotificationService$NotificationListener - Process id   : 50691

Any clue is really appreciated.

**Comment by mlusetti** [comment]
BTW In this configuration I after a period of time (a couple of minutes or little more) of inactivity I start to loose notifications.
I restart the app and everything is fine again.

Does this rings any bells ?

**Comment by kdubb** [comment]
Your detailed description may have solved this for everybody :+1: 

The Connection class uses weak references in it's map to hold notifications listeners.  The funny thing is... I can only attribute the reasoning to my many years of Cocoa/Objectice-C experience with spotting and fixing retain cycles; clearly this isn't an issue in Java and my "fix" for this non-issue may actually be creating an issue!

**Comment by kdubb** [comment]
Try #233 and see if this fixes your issues

**Comment by mlusetti** [comment]
Glad to be useful, someway.
BTW I'm going to try this in the next days, hopefully, now we've gone preprod and cannot make any kind of disruptive changes. We've fallen back to plain jdbc driver.
Thank you for your attention.

**Comment by kdubb** [comment]
#233 is merged.  Feel free to reopen if it didn't fix your issue.
