### ISSUE TITLE
All PGSQLIntegrityConstraintViolationException information derived from Notice is null

### ISSUE THREAD

**Issue by geraldodev** [impossibl/pgjdbc-ng#249]
Hi,

I'm getting null for every information derived from notice.

It would be nice if we could have column, table and so on in a structured way on constraint violation exception.

Postgres 9.5.1
Java 1.8.0_74
Our beloved 0.6

Regards,

Geraldo Lopes de Souza

**Comment by kdubb** [comment]
Using 9.5.3, Java 1.8 and the current head of development this seems to be working for me...
![screen shot 2016-07-09 at 5 32 58 pm](https://cloud.githubusercontent.com/assets/787655/16711015/5fabbc78-45fb-11e6-89e2-bb5478b7aa4a.png)

We actually rely on this information for generating error messages.  What exactly is not working for you?

**Comment by geraldodev** [comment]
Sorry for the delayed response,

It was a null constraint domain error.

{:column nil, :constraint nil, :table nil, :sql-state "23502", :error-code 0, :cause nil}

I got similar result of yours when I've changed it to not null.

{:column nil, :constraint "usuario_email_idx", :table "usuario", :sql-state "23505", :error-code 0, :cause nil}

Regards,

geraldodev
