### ISSUE TITLE
npe when setting date to null

### ISSUE THREAD

**Issue by seaneagan** [impossibl/pgjdbc-ng#253]
When attempting to set a date to null:

``` java
ps.setDate(1, null);
```

I get the following stack trace:

```
java.lang.NullPointerException
at com.impossibl.postgres.datetime.instants.Instants.fromDate(Instants.java:239)
at com.impossibl.postgres.jdbc.PGPreparedStatement.setDate(PGPreparedStatement.java:556)
at com.impossibl.postgres.jdbc.PGPreparedStatement.setDate(PGPreparedStatement.java:538)
```

`Instants.fromDate` is being passed a null that it is not expecting.

I am on version `0.7-SNAPSHOT`.

**Comment by kdubb** [comment]
This is easily fixed and I'll look to fix it ASAP.  Until then `setNull(0, Types.DATE)` should be a workaround.

**Comment by seaneagan** [comment]
Thanks for the quick response, and awesome project!

Yes I am using that workaround, of course the bad thing about it is it requires an if / else if you don't know whether the value is null or not.

Also I am seeing the same issue with `ps.setTimestamp(1, null)` / `Instants.fromTimestamp`.
