### ISSUE TITLE
SQLText throws ParseException for \''

### ISSUE THREAD

**Issue by mishako** [impossibl/pgjdbc-ng#254]
I'm tying to execute this SQL query:

``` sql
SELECT '\''';
```

I can do it in `psql`:

```
test=# SELECT '\''';
 ?column?
----------
 \'
(1 row)
```

But not in pgjdbc-ng:

``` java
conn.prepareStatement("SELECT '\\'''");
```

It throws:

```
java.sql.SQLException: Error parsing SQL at position 11 (SELECT '\'''): Error near: '
 at com.impossibl.postgres.jdbc.PGConnectionImpl.parseSQL(PGConnectionImpl.java:418)
 at com.impossibl.postgres.jdbc.PGConnectionImpl.prepareStatement(PGConnectionImpl.java:982)
```

The root cause is `ParseException` in `com.impossibl.postgres.jdbc.SQLText`:

``` java
new SQLText("SELECT '\\'''");
```

It throws:

```
java.text.ParseException: Error near: '
  at com.impossibl.postgres.jdbc.SQLText.parse(SQLText.java:228)
```

The problem is that the code in `SQLText` always considers backslash being an escape character:

``` java
if (c == '\'') {
  if (sql.charAt(ndx - 1) == '\\') {  // look-behind
    // skip escaped
  }
```

Since Postgres 9.1 (released 5 years ago) backslash is not an escape character unless it is placed inside a non-standard-conforming string (`E''`). `SQLText` doesn't seem to have knowledge about whether a string literal is standard-conforming or not, so for strings like `\''` it tries it's best to handle both standard (`''`) and non-standard (`\'`) ways of escaping, i.e. runs after two hares and fails.

**Edit: disregard the text below, I got an answer in the comments**

I'm also not sure about the purpose of `SQLText` class. In some cases it parses SQL incorrectly, but the code that calls `new SQLText()` is only using `SQLText::toString()`. So the whole SQL execution works only because the string representation of the resulting `SQLText` happens to be correct, even if the underlying data structures are not.

For example consider this code:

``` java
new SQLText("SELECT ''''").getFirstStatement().getNodeCount(); // 4
```

`SQLText` incorrectly parses the query into 4 pieces: `SELECT`, whitespace, empty string literal, empty string literal. Instead of two empty string literals there had to be one string literal `'`. Coincidentally the string representation doesn't change though. Two empty string literals (`''` and `''`) are represented as four single quotes `''''`. Same representation has one string literal with a single quote inside. So the query that gets send to Postgres is in the end correct.

What I want to say is why parse the query and risk failing if we call `toString` anyway. But I guess it doesn't really matter as long as we fix the bug.

**Comment by kdubb** [comment]
JDBC SQL is not PostgreSQL.  JBDBC requires `escape syntax` processing; not to be confused with string escaping.  SQLText's main aim is to process a JDBC SQL string into the proper PostgreSQL.

In addition to handling escape syntax SQL also handles understanding enough of the SQL to detect special conditions like multiple statements in a string, etc.

With fairly simple SQL it means that much of the time it may seem to do nothing but it is essential.

**Comment by mishako** [comment]
@kdubb Thank you for explanation! So `SQLText` doesn't have to fully and correctly understand SQL as long as it can detect important cases and doesn't break. I will edit the issue.
