### ISSUE TITLE
bind message has 32 result formats but query has 4 columns

### ISSUE THREAD

**Issue by hacheni** [impossibl/pgjdbc-ng#257]
Hi,

For some reasons and depending of the database use, we often have the following message :

bind message has 32 result formats but query has 4 columns

When analysing the database query log, we found that the request query done by the driver does not correspond to the database response. In another meaning, it seems like there is shift between queries sent to the database and the driver analysis of the response.

We also noticed that this error does never happen with the official postgresql driver.

Any help to figure out this problem please ?

Best regards

**Comment by kdubb** [comment]
Can you provided the SQL, stack trace, etc.  Even better would be a test case that exhibits the issue.

**Comment by kdubb** [comment]
Closing due to age and no new information. Feel free to comment with more data and we can re-open.
