### ISSUE TITLE
Please move TimestampUtils.java from test to main for JSON parsing

### ISSUE THREAD

**Issue by gallenc** [impossibl/pgjdbc-ng#279]
enhancement request:
I found that the Postgreslql JSON function row_to_json(ROW) renders JSON timestamps in the Postgresql time stamp format which is complex to process in java. 

However the little class TimestampUtils.java in the  pgjdbc-ng  test jar is very useful for converting between the somewhat variable Postgresql time stamp format and a more usable time formats in Java. 
Could TimestampUtils.java be moved from test into the main jar so that it is more easily available for users of the pgjdbc-ng library without having to import all the test classes.

**Comment by jesperpedersen** [comment]
Could you submit a pull request for this ?

Put the class in the com.impossibl.postgres.utils package.

**Comment by kdubb** [comment]
TimestampUtils is no longer in our main code base (It's not used by the driver but it is used by the tests).  All the parsing is done via instances of Java8 date/time parsers. Not going to fix.
