### ISSUE TITLE
0.7 release now that we have jsonb support?

### ISSUE THREAD

**Issue by andreak** [impossibl/pgjdbc-ng#280]

**Comment by kdubb** [comment]
🎱  says... Coming soon?!

The current code has some issues with ByteBuf memory leaks that I've yet to completely kick. Once I get time to debug those... 0.7 will be released

**Comment by andreak** [comment]
Nice!

**Comment by kdubb** [comment]
You can help by trying latest and seeing if you see any warnings about ByteBuf leaks!

**Comment by andreak** [comment]
Trying it out now.

**Comment by andreak** [comment]
Anything I can do to trigger any potential warnings about the leaks?

**Comment by oscerd** [comment]
Any news about a new release? Thanks guys.

**Comment by kdubb** [comment]
@oscerd I'm still tracking down leaks. We use the SNAPSHOT on a daily basis and see very few of them but they're still there.  I definitely want to clean those up before a release.

**Comment by oscerd** [comment]
Thanks :-)

**Comment by kdubb** [comment]
@jesperpedersen My `mvn clean package` has been run quite a few times now with no sign of ByteBuf leaks.  Are you seeing the same or do we still have leaks to track down?

I'd like to release a 0.7 if the leaks are cleaned up.

**Comment by jesperpedersen** [comment]
@kdubb Still seeing the leaks - should I merge https://github.com/jesperpedersen/pgjdbc-ng/tree/bytebuf to get closer to a ByteBuf usage API ?

**Comment by jesperpedersen** [comment]
Watch #297
