### ISSUE TITLE
Deadlock when executing a SQL query within a PGNotificationListener

### ISSUE THREAD

**Issue by obraliar** [impossibl/pgjdbc-ng#284]
I'm trying to execute an SQL `SELECT` query after receiving a notification with `PGNotificationListener` using the same connection where the listener has been registered. The program neither executes the query nor it's terminating. A minimal example is provided at https://github.com/obraliar/pgjdbc-ng-test/blob/master/src/test/java/ConnectionCastTest.java#L23.

[Travis](https://travis-ci.org/obraliar/pgjdbc-ng-test/builds/162051391#L274) simply runs into 10 minutes timeout. Locally, the tests always fail, on the current travis build, the test goes through.

**Comment by kdubb** [comment]
Reusing the same connection inside the listener callback's thread will not work. The connection is still executing the notification code from the server and will result in a deadlock; as you are seeing.

My recommendation is to start a task via the service to do whatever it is you need. This will all the callback thread to complete and you'll be able to reuse the connection at that point.
