### ISSUE TITLE
PGPreparedStatement#setArray conflicts with Arrays.BinEncoder

### ISSUE THREAD

**Issue by yrashk** [impossibl/pgjdbc-ng#288]
`Arrays.BinEncoder` seems to expect an actual Java array, however if one uses `PreparedStatement#setArray(n, Array)` Array is what gets down to `Arrays.BinEncoder` and it fails with `IllegalArgumentException` on `java.lang.reflect.Array#getLength`.

If, instead, `PreparedStatement#setArray(n,Array#getArray())` is used, everything works just fine.

Am I misunderstanding something or is this a bug?

P.S. What's also interesting is that seemingly passing Array into `createStruct` (in that case, the Array will be a part of some structure), then it works without a problem.

**Comment by jesperpedersen** [comment]
Please, provide a test for ArrayTest that verifies this scenario, and the necessary code changes to get it passing.

Thanks in advance !
