### ISSUE TITLE
Is java.util.UUID supported in batch updates?

### ISSUE THREAD

**Issue by jszczepankiewicz** [impossibl/pgjdbc-ng#290]
I have an impression that there is some bug when using java.util.UUID in insert using batches. When I use separately like below (Kotlin):
```
val query = "UPDATE entities SET updated=?, body=? WHERE id=?"
            conn = dataSource.connection
            insert = conn.prepareStatement(query)

            insert.setTimestamp(1, Timestamp.valueOf(entity.updated))
            insert.setBinaryStream(2, entity.body.inputStream())
            insert.setObject(3, entity.id)
            insert.executeUpdate()
```
everything looks fine (entity.id is of type UUID where column id is declared on Postgresql level also as UUID). But trying to do similar in batch like:
```
 val query = getInsertIntoIndexSql(entityName, columns)

            conn = dataSource.connection
            insert = conn.prepareStatement(query)

            for(entity in entities) {
                var i = 1
                insert.setObject(i++, (entity["id"] as UUID))

                for((columnName, columnType) in columns){
                    LOG.warn("XX: {} => {}", columnName, columnType)
                    when (columnType) {
                        BOOL -> insert.setBoolean(i++, entity[columnName] as Boolean)
                        TEXT -> insert.setString(i++, entity[columnName] as String)
                        TIMESTAMP_WITHOUT_TZ -> insert.setTimestamp(i++, Timestamp.valueOf(entity[columnName] as LocalDateTime))
                        BINARY -> insert.setBinaryStream(i++, (entity[columnName] as ByteArray).inputStream())
                    }
                }
                insert.addBatch()
            }

            insert.executeBatch()
```
results in:

> java.lang.ClassCastException: java.util.UUID cannot be cast to java.io.InputStream
> 
> 	at com.impossibl.postgres.system.procs.Bytes$BinEncoder.length(Bytes.java:175)
> 	at com.impossibl.postgres.protocol.v30.ProtocolImpl.lengthOfParams(ProtocolImpl.java:724)
> 	at com.impossibl.postgres.protocol.v30.ProtocolImpl.writeBind(ProtocolImpl.java:508)
> 	at com.impossibl.postgres.protocol.v30.BindExecCommandImpl.execute(BindExecCommandImpl.java:319)
> 	at com.impossibl.postgres.protocol.v30.ProtocolImpl.execute(ProtocolImpl.java:370)
> 	at com.impossibl.postgres.jdbc.PGConnectionImpl.execute(PGConnectionImpl.java:438)
> 	at com.impossibl.postgres.jdbc.PGPreparedStatement.executeBatch(PGPreparedStatement.java:368)
> 	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
> 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
> 

Is this known issue?

**Comment by jszczepankiewicz** [comment]
Small update. I found test:
https://github.com/impossibl/pgjdbc-ng/blob/fcfe2e8774eb8942c3cdfe3bba06fdca7842f300/src/test/java/com/impossibl/postgres/jdbc/UUIDTest.java
but looks it is not testing batch updates. Nonetheless changing to:
`insert.setObject(i++, (entity["id"] as UUID),Types.OTHER)`
in batch and issue still persist.

**Comment by jesperpedersen** [comment]
Please, provide a new test for UUIDTest that executes this scenario, and the necessary code changes to get it passing.

Thanks in advance !

**Comment by jszczepankiewicz** [comment]
I'm sorry my mistake :(. Everything is fine with pgjdbc-ng in this aspect it was just mistake in my test cases. Althrough I found some real bug which I will try to fix soon as seems to be easy fix (related to how Long is handled in pgjdbc-ng.
