### ISSUE TITLE
pgjdbc-ng 0.7

### ISSUE THREAD

**Issue by jesperpedersen** [impossibl/pgjdbc-ng#297]
Release items:
* ~~Align SSL configuration for connection level vs. DataSource~~
* ~~Remove work branches from repository~~
* ~~Create artifacts with Java 7~~
* ~~Deprecate Java 7 in release notes~~
* ~~Make PostgreSQL 9.1 best effort support (release notes)~~

Required fixes:
* ~~ByteBuf leak (#276)~~
* ~~https://github.com/netty/netty/issues/6246~~ (sort of, as we downgraded to Netty 4.1.4)

**Comment by oscerd** [comment]
Is there any estimated date for 0.7 release?

**Comment by jesperpedersen** [comment]
http://impossibl.github.io/pgjdbc-ng/releases/2017/01/20/0.7.html
