### ISSUE TITLE
OSGI package  version numbers over / under optimistic 

### ISSUE THREAD

**Issue by sesuncedu** [impossibl/pgjdbc-ng#309]
The OSGI package version numbers in releases of pgjdbc to date have been  over and under optimistic, which I think means the glass is full, but it's only a half. 

Some packages have not had visible API changes since the first release with bundle headers (0.3), but most have had at least one non-backwards compatible change. 

Versions 0.7 was the first release with non 0 version numbers - all 0.7.0.
Version 0.7.1 bumped every package version  to 0.7.1. In most cases this was unnecessary, but for .jdbc, there were minor level changes that should have given that package a version of 0.8.0 or higher. 

I have submitted a PR that adds a package-info.java to each package with a safe version number. 
Packages with unchanged APIs since jar version 0.3 have been given version 0.7.1. Other packages, with at least one major API change since 0.3 have been given version 1.0.0. 
This is safe, since there have been no packages versions with a major > 0.

I have also set up the Felix bundle plugins baseline goal, attached to the  verify phase. It will issue warnings about version numbers being increased too much, because it is using the latest release as the baseline version, so doesn't know about past problems.  These warnings will stop if a release is made with the new package versions, and are not set to break the build. 
Changes that affect the api will cause errors, with suggestions for replacement package versions. The Felix output displays any api diff in a friendlier fashion than the bnd plugin. 

Whilst I was changing the bundle plugin settings, I also removed the explicit versioning for netty-io, as the import versions are correctly  generated from the dependencies. I also enabled self-import of pgjdbc packages, which can be useful at times. 

I did not make any changes to which packages are exported ; it can be useful to avoid exposing private packages. 
I also did not change the settings of any JRE imports to make them optional. Thus the bundle cannot be resolved  if the javax.xa packages aren't available (this will be an issue with jigsaw, which hides them by default). 
But then again, everything is an issue with jigsaw.

**Comment by kdubb** [comment]
Replaced with #372
