### ISSUE TITLE
DataSource configuration issues:

### ISSUE THREAD

**Issue by sesuncedu** [impossibl/pgjdbc-ng#315]
1.  The name of the standard datasource property for storing "name of a particular database on a server" is "databaseName"; pgjdbc-ng uses "database". 
2. The name of the standard datasource property for storing the "database server name" is "serverName"; pgjdbc-ng uses "host".
3. The name of the standard datasource property for storing the "port number where a server is listening for requests" is "portNumber"; pgjdbc-ng uses "port".
4. pgjdbc-ng does not support the "description" property, which is apparently the only required property. 

  (JDBC 4.2 specification, §9.6.2 DataSource Properties) 

Additionally, most  drivers (including pgjdbc-TOS)  support the "url" property.

**Comment by kdubb** [comment]
Fixed in #360
