### ISSUE TITLE
PGNotificationListener extends NotificationListener instead of vice versa

### ISSUE THREAD

**Issue by sesuncedu** [impossibl/pgjdbc-ng#318]
The API class ```com.impossibl.postgres.api.jdbc.PGNotificationListener``` is defined as: 
```java
import com.impossibl.postgres.system.NotificationListener;
[...]
public interface PGNotificationListener extends NotificationListener {
}
```
Where ```com.impossibl.postgres.system.NotificationListener```  is defined as 

```java
public interface NotificationListener {
  void notification(int processId, String channelName, String payload);
}
```

This requires  ```NotificationListener``` to be exported as part of the public API. 
The declaration of ```NotificationListener::notification``` could be moved to PGNotificationListener, and NotificationListener could be defined as extending PGNotificationListener. Alternatively, all references to NotificationListener could be changed to refer to NotificationListener.

**Comment by kdubb** [comment]
`NotificationListener` has been removed in #356
