### ISSUE TITLE
com.impossibl.postgres.api.data.Record uses com.impossibl.postgres.types.Type

### ISSUE THREAD

**Issue by sesuncedu** [impossibl/pgjdbc-ng#319]
Type is deeply  tied in to many low-level implementation classes, such as  ```PgType.Row``` and ```PgAttribute.Row``` .

If ..api.data.* is part of the public api, then it might be better to add an Interface for the methods that are intended to be part of the public api, and have Type  implement that interface.

**Comment by kdubb** [comment]
`Record` is gone. JDBC `Struct` should be expected/used.
