### ISSUE TITLE
NullPointerException when we get Locale Specification

### ISSUE THREAD

**Issue by manuwit** [impossibl/pgjdbc-ng#325]
On a windows postgre database with a Local as "French_France.1252", the following code cannot work:

Class BasicContext line 290:
      if (Locales.getJavaCompatibleLocale(localeSpec.split("\\.")[0]) != null) {
        localeSpec = Locales.getJavaCompatibleLocale(localeSpec);
      }
The localeSpec is null and throws an exception in the next call:
      String[] localeIds = localeSpec.split("_|\\.");

For my case, I propose this solution:
localeSpec = Locales.getJavaCompatibleLocale(localeSpec.split("\\.")[0]));

But maybe, it will be great to avoid null returned value ...

**Comment by kdubb** [comment]
Fixed in #349
