### ISSUE TITLE
Unable to express ? Operator

### ISSUE THREAD

**Issue by uweschaefer** [impossibl/pgjdbc-ng#326]
Am i right assuming, there is no way to get WHERE a ? 'b' through to the database with a PreparedStatement?

I understand the JDBC Spec prevents us from using ?.

I tried to work around with
* ??
* {postgres '?'}
* {postgres containskey}

but i am out of ideas.

**Comment by guai** [comment]
I once hit similar issue with db2
try fill this jdbc-parameter with '?' char
though this is not what one would do on regular basis

**Comment by kdubb** [comment]
This is an old issue that should have been closed a while ago... escaping `?` using `??` has been supported since b41dac82b1f4b7fc7ae2f2315d49eaf1c0459d69. If that's not working for you feel free to reopen.
