### ISSUE TITLE
Version 0.7.1 fails with pg10rc1

### ISSUE THREAD

**Issue by andreak** [impossibl/pgjdbc-ng#336]
Caused by: java.lang.IllegalArgumentException: revision cannot have value when minor does not
        at com.impossibl.postgres.system.Version.<init>(Version.java:80)
        at com.impossibl.postgres.system.Version.get(Version.java:66)
        at com.impossibl.postgres.system.Version.parse(Version.java:50)

select version();
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                 version                                                  │
├──────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ PostgreSQL 10rc1 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406, 64-bit │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────┘

**Comment by andreak** [comment]
Maybe having this as Version.VERSION_SPLIT_PATTERN:
```  private static final Pattern VERSION_SPLIT_PATTERN = Pattern.compile("((?:\\D+)?\\D+)");```

**Comment by andreak** [comment]
This now applies to 11rc1 as well.

**Comment by kdubb** [comment]
Fixed in e2cc1633c889cf0cb254488a3c53bb58dc3bc07e
