### ISSUE TITLE
PGDataSource.getConnection could return a PGConnection, but doesn't

### ISSUE THREAD

**Issue by npryce** [impossibl/pgjdbc-ng#338]
At the moment, if you get a connection from a PGDataSource you cannot add notification listeners without casting to PGConnection.  This would be avoided if the getConnection methods returned PGConnection.

**Comment by jesperpedersen** [comment]
PGDataSource.getConnection is the official contract from javax.sql.DataSource, so I don't see how you can get around that.

We could add another method to get PGConnection, but then you have to cast DataSource to PGDataSource.

Our DataSource instance could be "proxied" by different connection pools, incl our Connection instance, so there is no easy way to account for this scenario.

Doing the casting in client code, if the returned instance is a PGConnection, is the correct way IMHO

**Comment by npryce** [comment]
It shouldn’t be a problem because Java has covariant return types

**Comment by kdubb** [comment]
@npryce After looking at the code. A covariant return of `PGConnectionImpl` is possible here to make life easier.  Not sure how much easier since you're almost always using a connection pool which will be returning a basic `Connection`.

**Comment by npryce** [comment]
Thanks.

It’s useful in code that receives notifications, because it maintains a single long-lived connection, and needs to register a listener with methods that exist on PGConnection

**Comment by brettwooldridge** [comment]
Do not do this.  The official API is to call the unwrap() method on the Connection, passing PGConnection.class as the parameter.

**Comment by kdubb** [comment]
Good call. Right API for the job.
