### ISSUE TITLE
What if the connection is lost ?

### ISSUE THREAD

**Issue by d3bt3ch** [impossibl/pgjdbc-ng#339]
I am registering a listener with the database server for notifications. What if there is a network failure or the database server is rebooted ?

**Comment by vaIgarashi** [comment]
bump

**Comment by stodge** [comment]
I am also interested in knowing this.

**Comment by davecramer** [comment]
The connection drops and you do not get notified.

**Comment by kdubb** [comment]
As of #356, `PGNotificationListener` has a `closed` method to notify listeners when the connection is closed; you can now make a new connection or handle it some other way.
