### ISSUE TITLE
NullPointerException when we get Locale Specification for Spanish_Spain.1252 locale

### ISSUE THREAD

**Issue by juanfrasco** [impossibl/pgjdbc-ng#340]
This is exactly the same issue  pointed by manuwit (#325) but for the spanish locale, 
(using pgjdbc-ng-0.7.1-complete.jar)

On a windows postgres database with a Local as "Spanish_Spain.1252", the following code cannot work:

Class BasicContext line 290:
if (Locales.getJavaCompatibleLocale(localeSpec.split("\.")[0]) != null) {
localeSpec = Locales.getJavaCompatibleLocale(localeSpec);
}
The localeSpec result from Locales.getJavaCompatibleLocale(localeSpec) is null and 
throws an exception in the next call:
String[] localeIds = localeSpec.split("_|\.");

The same #325 solution applies here:
localeSpec = Locales.getJavaCompatibleLocale(localeSpec.split("\.")[0]));

**Comment by kdubb** [comment]
Fixed in #349
