### ISSUE TITLE
PGConnection cannot be resolved to a type after upgrading to 0.7.1

### ISSUE THREAD

**Issue by stodge** [impossibl/pgjdbc-ng#342]
I changed my pom.xml to upgrade from 0.7 to 0.7.1 from https://mvnrepository.com/artifact/com.impossibl.pgjdbc-ng/pgjdbc-ng/0.7.1:

```
<dependency>
    <groupId>com.impossibl.pgjdbc-ng</groupId>
    <artifactId>pgjdbc-ng</artifactId>
    <version>0.7.1</version>
</dependency>
```

I'm getting many compile errors: 

```
PGConnection cannot be resolved to a type
PGConnectionPoolDataSourceObjectFactory cannot be resolved to a type
PGNotificationListener cannot be resolved to a type
```

I browsed the source code and I can't see why I'm getting these errors from the updated library. Any suggestions for a relatively mild Java developer?

Thanks

**Comment by kdubb** [comment]
First, apologies for the lack of response.  This seems to be a dependency management issue unrelated to the driver iteself as the `PGConnection` interface is, and will remain, available.
