### ISSUE TITLE
How to map composite nested types into Java classes

### ISSUE THREAD

**Issue by relio** [impossibl/pgjdbc-ng#344]
Hi all!
I'm playing with composite nested types and I'm trying to map them into Java classes but I have some questions about how to do this in the right way. 

These are the step I made:

1. I have created two linked table (SUBJECTS and ADDRESSES), two types and a function to read data from tables:

```sql
CREATE TYPE personal_data.TYPE_ADDRESS AS
(
  ID_ADDRESSES bigint,
  ID_SUBJECT bigint,
  STREET VARCHAR(80),
  ZIP VARCHAR(5),
  CITY VARCHAR(50),
  COUNTRY_CODE CHAR(3),
  ADDRESS_TYPE CHAR(1)
);

CREATE TYPE personal_data.TYPE_SUBJECT AS
(
  ID_SUBJECT bigint,
  NAME VARCHAR(100),
  SURNAME VARCHAR(100),
  SEX CHAR(1),
  ADDRESSES_ARRAY personal_data.TYPE_ADDRESS[]
);
```
Finally I have filled the tables with some fake data (complete SQL script available here, inserts not provided):
[ScriptNestedTypeExample.txt](https://github.com/impossibl/pgjdbc-ng/files/2342496/ScriptNestedTypeExample.txt)

2. I have generated the UDT Java classes from types using the jar pgjdbc-ng-udt-0.0.2-complete.jar (java extension changed to txt):
[T_Aypeddress.txt](https://github.com/impossibl/pgjdbc-ng/files/2342504/T_Aypeddress.txt)
[T_Sypeubject.txt](https://github.com/impossibl/pgjdbc-ng/files/2342505/T_Sypeubject.txt)

The UDT generator created a Subject class quite strange with a type adrress that I was not able to deal with as the `in.readObject()` method to populate the addresses:

```java
  private Long _Sidubject;
  private varchar name;
  private varchar surname;
  private bpchar sex;
  private _type_address _Aaddressesrray;

  ...

  @Override
  public void readSQL(SQLInput stream, String typeName) throws SQLException {
    PGSQLInput in = (PGSQLInput) stream;
    _Sidubject = in.readLong();
    name = in.readObject();
    surname = in.readObject();
    sex = in.readObject();
    _Aaddressesrray = in.readObject();    
  }
```
So I modified them into these:

[TypeAddress.java.txt](https://github.com/impossibl/pgjdbc-ng/files/2342510/TypeAddress.java.txt)
[TypeSubject.java.txt](https://github.com/impossibl/pgjdbc-ng/files/2342511/TypeSubject.java.txt)

3. Finally I wrote a test class: 

[TestCompositeNestedType.java.txt](https://github.com/impossibl/pgjdbc-ng/files/2342512/TestCompositeNestedType.java.txt)

Everything seems to work fine (at least the reading), but I'm a little bit puzzled by:

A. Why the UDT generator has 'shaked' the name of the Java classes and properties. May be there is a naming convention?
B. Where do these type come from in the original classes? I was not able to deal with them:

 private **bpchar** sex;
 private **_type_address** _Aaddressesrray;
 
C. Is this the right way to retrieve the nested property writing by hand a `getListFromArray` by hand or there is an out of the box solution and I'm just reinventing the wheel?

```java
    private List<TypeAddress> getListFromArray(Array arr, String typeName) throws SQLException {
        List<TypeAddress> result = null;

        if (arr != null) {
            Map<String, Class<?>> typeMap = new HashMap();
            typeMap.put(typeName, TypeAddress.class);

            final Object[] objectArray = (Object[]) arr.getArray(typeMap);
            List<TypeAddress> list = new ArrayList<>(objectArray.length);
            for (Object o : objectArray) {
                list.add(TypeAddress.class.cast(o));
            }
            result = list;
        }
        return result;
    }

    @Override
    public void readSQL(SQLInput stream, String typeName) throws SQLException {
        PGSQLInput in = (PGSQLInput) stream;
        _Sidubject = in.readLong();
        name = (String)in.readObject();
        surname = (String)in.readObject();
        sex = (String)in.readObject();
        addresses = getListFromArray(in.readArray(), "type_address");
    }
```
Thanks in advance!

**Comment by kdubb** [comment]
The new UDT generator (in `udt-gen` module). Handles these cases and the tests currently provide and example.
