### ISSUE TITLE
NullPointerException while connecting to Postges database

### ISSUE THREAD

**Issue by balnagendra** [impossibl/pgjdbc-ng#345]
Hi,
I was trying your pgjdbc-ng. Here is the code:
import java.sql.SQLException;
import java.sql.Statement;
 
import com.impossibl.postgres.api.jdbc.PGConnection;
import com.impossibl.postgres.jdbc.PGDataSource;

public class PGListenNotify
{
PGConnection connection;
 
public PGListenNotify()
{
String DBHost = System.getenv("DBHost");
String DBName = System.getenv("DBName");
String DBUserName = System.getenv("DBUserName");
String DBPassword = System.getenv("DBPassword");
try
{
PGDataSource dataSource = new PGDataSource();
dataSource.setHost(DBHost);
dataSource.setPort(5432);
dataSource.setDatabase(DBName);
dataSource.setUser(DBUserName);
dataSource.setPassword(DBPassword);
 
connection = (PGConnection) dataSource.getConnection();
Statement statement = connection.createStatement();
}
catch (SQLException e)
{
e.printStackTrace();
}
}

public static void main(String[] args)
{
PGListenNotify ln = new PGListenNotify();
}
}

But I am hit with this error:
Exception in thread "main" java.lang.NullPointerException
        at com.impossibl.postgres.system.BasicContext.loadLocale(BasicContext.java:294)
        at com.impossibl.postgres.system.BasicContext.init(BasicContext.java:273)
        at com.impossibl.postgres.jdbc.PGConnectionImpl.init(PGConnectionImpl.java:251)
        at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:182)
        at com.impossibl.postgres.jdbc.AbstractDataSource.createConnection(AbstractDataSource.java:723)
        at com.impossibl.postgres.jdbc.PGDataSource.getConnection(PGDataSource.java:66)
        at com.impossibl.postgres.jdbc.PGDataSource.getConnection(PGDataSource.java:58)
        at PGListenNotify.<init>(PGListenNotify.java:26)
        at PGListenNotify.main(PGListenNotify.java:37)

**Comment by ManuelB** [comment]
Hi,
this is similair to #340. We have the same issue with Germany_German.1252 Here is our workaround:

```
package com.impossibl.postgres.utils;

import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

public class GermanLocaleFixer {
	
	private static final Logger log = Logger.getLogger(GermanLocaleFixer.class.getName());
	
	public static void addGermanGermany1252ToLocales() {
		Class<?> classUtil;
		try {
			classUtil = Locales.class;

			// https://stackoverflow.com/questions/3301635/change-private-static-final-field-using-java-reflection
			Field implementationField = classUtil.getDeclaredField("LOCALES");
			implementationField.setAccessible(true);
			Field modifiersField = Field.class.getDeclaredField("modifiers");
			modifiersField.setAccessible(true);
			modifiersField.setInt(implementationField, implementationField.getModifiers() & ~Modifier.FINAL);

			// Reset the cache
			Map<String, String> LOCALES = (Map<String, String>) implementationField.get(classUtil);
			LOCALES.put("German_Germany.1252", "de_DE");
		} catch (NoSuchFieldException | SecurityException | IllegalArgumentException | IllegalAccessException e1) {
			log.log(Level.WARNING, "Problem with modifying LOCALES private final variable from com.impossibl.postgres.utils.Locales", e1);
		}
	}
}

```

Then in your code you have to call:
```
...
GermanLocaleFixer.addGermanGermany1252ToLocales();
...
```

Hope that helps

/Manuel

**Comment by kdubb** [comment]
Fixed in #349

@ManuelB @balnagendra  Please try the rework branch and report back

**Comment by ManuelB** [comment]
@kdubb thanks for the fix unfortunately I currently don't have time to verify it.

**Comment by balnagendra** [comment]
Dear @kdubb 
Build pgjdbc-ng is giving error:
```
λ .\gradlew.bat
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Script 'E:\TechHomeS\TechHomePostgreSQL\pgjdbc-ng-develop\driver\src\build\testing.gradle.kts' line: 150

* What went wrong:
View 'posix' not available

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2m 5s
```
I am building on Windows10.

**Comment by balnagendra** [comment]
@kdubb 
Thanks for your help. I was able to solve it. I am a novice in building with Gradle. That is why this confusion took place. I switched to CentOS and the problem was solved.
I got listener notification in Postgres.

Thanks
balnagendra
