### ISSUE TITLE
PgConnection.isValid(timeout) is not using the timeout sent in the argument

### ISSUE THREAD

**Issue by dineshudayakumar** [impossibl/pgjdbc-ng#346]
PgConnection.isValid(1) is not using the timeout sent in the argument.

This was my scenario
One periodic scheduler checks whether the PgConnection is valid or not using the PgConnection.isValid(1) to make sure the connection is not closed because of cases like restart of postgres
And there was a notification listener attached to the PgConnection to listen for events.
The periodic scheduler thread got stuck at isValid() and no events are getting posted to the notification listener

The timeout set in the argument was not used and periodic thread was stuck infinitely.

I had to replace the isValid to manually creating statement "SELECT 1" and setting query timeout in it to get pass this

Thank You,
Dinesh

**Comment by kdubb** [comment]
Fixed in #349
