### ISSUE TITLE
pgjdbc-ng seems incompatible with Flyway 5.x

### ISSUE THREAD

**Issue by amyodov** [impossibl/pgjdbc-ng#347]
I recently tried to upgrade my project (successfully using pgjdbc-ng 0.7.1 and Flyway 4.2.0) to Flyway 5.2.0, and it failed to launch, got stuck at the Flyway migration start.

Even though Flyway doesn’t support pgjdbc-ng officially (what is a separate problem that would worth to be fixed), it worked rather well before: you just create a `PGDataSource` instance:

~~~java
final PGDataSource dataSource = new PGDataSource() {{
            setHost(dbHost);
            setPort(dbPort);
            setDatabase(dbDatabase);
            setUser(dbUser);
            setPassword(dbPassword);
        }};
~~~

... and then use it:

~~~java
final Flyway flyway = new Flyway() {{
            setDataSource(dataSource);
            setLocations(...);
        }};
~~~

With Flyway 5, this last line could be changed to something like this:

~~~java
final Flyway flyway = Flyway
                .configure()
                .dataSource(dataSource)
                .locations(...)
                .load();
~~~

Though now it gets stuck on the attempt of migration. I traced it to around getting stuck at `connection.lock()`, but no luck further.

**Comment by kdubb** [comment]
Fixed in #349
