### ISSUE TITLE
Update Netty dependency to newer version?

### ISSUE THREAD

**Issue by stodge** [impossibl/pgjdbc-ng#348]
The version of Netty that you are using is fairly old. Would it be possible to update to a newer version?

Thanks

**Comment by stodge** [comment]
There's been no repository activity for a year; I assume this project has been abandoned? Any alternatives or stable forks?

**Comment by davecramer** [comment]
Well there is this https://github.com/pgjdbc/pgjdbc

Dave Cramer

**Comment by kdubb** [comment]
Being updated in #349
