### ISSUE TITLE
pgjdbc-ng needs an implementation of java.sql.DataSource

### ISSUE THREAD

**Issue by brettwooldridge** [impossibl/pgjdbc-ng#35]
A transaction manager that I use (bitronix) requires a DataSource instead of a Driver, so I am unable to test pgjdbc-ng in our product yet.  Another product of ours uses the HikariCP connection pool, which also only supports DataSources.  java.sql.DataSource is the "preferred" way to obtain connections since Java 1.4.  According to the JavaDoc for DataSource:

"An alternative to the DriverManager facility, a DataSource object is the preferred means of getting a connection."

**Comment by kdubb** [comment]
Follow issue #21 @jesperpedersen is currently working on it
