### ISSUE TITLE
Transfer wiki to documentation

### ISSUE THREAD

**Issue by kdubb** [impossibl/pgjdbc-ng#376]
All the information in the wiki that is not project related should be moved into the documentation to be versioned and released as normal.

**Comment by kdubb** [comment]
I've deleted most of the wiki information, as it is already covered in the documentation.

@jesperpedersen Are the WildFly wiki pages still relevant and up-to-date? If I'll transfer them to docs and delete the pages.

**Comment by jesperpedersen** [comment]
Yeah, they should be - apart from the version number of the driver

**Comment by brettwooldridge** [comment]
@kdubb @jesperpedersen It was my impression that the github wiki is essentially a separate git repository, and can be versioned independently of the driver.  For example, the git repo for my github's project wiki is at ``git@github.com:brettwooldridge/HikariCP.wiki.git``.  And I manage it separately as a repository.

**Comment by jesperpedersen** [comment]
Frankly, I think keeping it in the documentation is best. Otherwise there are 2 places where people has to contribute to.

**Comment by kdubb** [comment]
@brettwooldridge Agreed but now that we have automatically built documentation I want to consolidate all that information into a single place. The `gh-pages` push is versioned to the release therefore documentation will be available historically for each release. The wiki would need extra care to keep in sync.
