### ISSUE TITLE
setApplicationName fails with setClientInfo, application.name=REASON_UNKNOWN_PROPERTY

### ISSUE THREAD

**Issue by mlillywhite** [impossibl/pgjdbc-ng#388]
I use setApplicationName in 0.7.0, but in the latest release (0.8.2) this seems to cause a SQLClientInfoException with the application.name=REASON_UNKNOWN_PROPERTY property.

**Comment by mlillywhite** [comment]
On further investigation this appears to be caused by me calling getClientInfo() and then later calling setClientInfo().

**Comment by kdubb** [comment]
`setClientInfo` was changed to accept the JDBC defined values, and leaves out a number of alternatives.

Use the JDBC defined `ApplicationName` instead.

**Comment by kdubb** [comment]
@mlillywhite Closing, feel free to re-open if an issue is discovered
