### ISSUE TITLE
Javadoc search links are broken

### ISSUE THREAD

**Issue by robertfw** [impossibl/pgjdbc-ng#390]
The links provided by the search window input in the Javadoc are broken. There is a stray `/undefined/` path element that, once removed, results in the correct link.

E.g.
One of the links provided when searching "isValid":
http://impossibl.github.io/pgjdbc-ng/docs/current/javadoc/undefined/com/impossibl/jdbc/spy/ConnectionRelay.html#isValid(int) - result: 404

Removing /undefined/, so the link is now http://impossibl.github.io/pgjdbc-ng/docs/current/javadoc/com/impossibl/jdbc/spy/ConnectionRelay.html#isValid(int) - result: loads as expected

**Comment by kdubb** [comment]
@robertfw I'm a little loath to admit I'm not sure where you're encountering these links... where is the "search window input"?

**Comment by kdubb** [comment]
@robertfw Found it! Didn't even know that existed 🤷‍♂️
