### ISSUE TITLE
java.lang.IndexOutOfBoundsException : Invalid array range: 1 to 1 on start

### ISSUE THREAD

**Issue by lospejos** [impossibl/pgjdbc-ng#391]
java.lang.IndexOutOfBoundsException : Invalid array range: 1 to 1 on start

I have `java.lang.IndexOutOfBoundsException : Invalid array range: 1 to 1` exception when starting test java application which uses `pgjdbc-ng` driver version 0.8.2

Some details:
I'm on Windows 10 with locale set to Russian.
I use PostgreSQL server version 11.2 x64 unpacked from zip binaries (crossover mode).
Also I use Java 8 x64 (java version "1.8.0_201").

When I searched stack trace I found code in class `com.impossibl.postgres.system.BasicContext` method `private void loadLocale()`:

`
  case "lc_numeric":
    Locale numLocale = new Locale.Builder().setLanguageTag(localeIds[0]).setRegion(localeIds[1]).build();` 

In debugger, variable `localeSpec` has value `ru`. Thus evaluating `localeIds[1]` leads to an IndexOutOfBoundsException.

Consider making this code more safe when working with `localeSpec` with values without underscores. F. e. please check if this code is applicable:

`
.setRegion(localeIds.length()>1 ? localeIds[1] : localeIds[0])
`

**Comment by lospejos** [comment]
Moreover, I found this:
https://dba.stackexchange.com/a/172838/141428

In short, on Windows 8+, PostgtreSQL database locale is set as "en-US" but not "en_US".

**Comment by kdubb** [comment]
I'm pretty sure Windows will be the death of me.  I'll have to look into how to fix this properly.  I did _some_ tests on Window to get to the current code but clearly it's not enough.

**Comment by kdubb** [comment]
@lospejos  #431 Tackles a lot of locale issues and I believe should cover this issue as well.  Would you be able to test in your same environment to validate the fixes?
