### ISSUE TITLE
LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information. Recent access records

### ISSUE THREAD

**Issue by lyguan** [impossibl/pgjdbc-ng#415]
Hi,  I found a exception here.  I planed to update an array which item of array is a customized type,
and this array has 300 hundreds items.  When I ran the code, it throw
io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:331)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:171)
	io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:105)
	com.impossibl.postgres.jdbc.PGBuffersArray.encode(PGBuffersArray.java:131)
	com.impossibl.postgres.jdbc.PGBuffersArray.encode(PGBuffersArray.java:110)
	com.impossibl.postgres.jdbc.PGBuffersArray.encode(PGBuffersArray.java:92)
	com.impossibl.postgres.jdbc.PGDirectConnection.createArrayOf(PGDirectConnection.java:1197)
	com.morningstar.equitydata.lib.postgresql.dao.FinancialReportSQLDataDao.addOrUpdate(FinancialReportSQLDataDao.java:118)
	com.morningstar.equitydata.lib.postgresql.dao.FinancialReportSQLDataDao.lambda$addOrUpdate$0(FinancialReportSQLDataDao.java:56)
	java.util.ArrayList.forEach(ArrayList.java:1249)
	com.morningstar.equitydata.lib.postgresql.dao.FinancialReportSQLDataDao.addOrUpdate(FinancialReportSQLDataDao.java:54)
	com.morningstar.equitydata.postgresqldata.synchronize.services.FinancialReportSyncService.addOrUpdate(FinancialReportSyncService.java:77)
	com.morningstar.equitydata.postgresqldata.synchronize.services.FinancialReportSyncService.lambda$EventHandle$0(FinancialReportSyncService.java:131)
	java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)

**Comment by tlf30** [comment]
Did you close all resources before garbage collection tried to destroy the objects?

**Comment by lyguan** [comment]
@tlf30 Thanks for your help. I have found the solution here.  https://github.com/impossibl/pgjdbc-ng/issues/389,  you met the same error before.
