### ISSUE TITLE
With JDBI3 - org.jdbi.v3.core.ConnectionException: java.sql.SQLException: Unwrap error

### ISSUE THREAD

**Issue by rsimonton** [impossibl/pgjdbc-ng#418]
I'm getting an "Unwrap Exception" trying to use the driver in concert with JDBI.  I've posted the details over at StackOverflow, hopefully it's ok if I just link to it instead of rehashing the post, thanks.

https://stackoverflow.com/questions/56588224/sqlexception-unwrap-error-with-jdbi-and-pgjdbc-ng-postres-driver

**Comment by kdubb** [comment]
I believe the answer is to stop using `PostgresPlugin`.  Read my StackOverflow answer for the details.
