### ISSUE TITLE
Getting a ServiceLoader error

### ISSUE THREAD

**Issue by ccleve** [impossibl/pgjdbc-ng#427]
I posted this on StackOverflow a while ago and didn't get an answer:

https://stackoverflow.com/questions/57632541/pgjdbc-ng-throws-mysterious-serviceloader-error

The problem went away on its own after a while, but now it's back. Closing and reopening Eclipse no longer solves it.

I'm using version 0.8.2.

A full clean / rebuild does not fix it. Is there some dependency which is missing?

**Comment by kdubb** [comment]
@ccleve It appears this is the exact same issue, located earlier on, as #417.  Are you good with closing this and putting your details over there or do you think these are different problems?

**Comment by ccleve** [comment]
It does look like it's the same issue. Closing...
