### ISSUE TITLE
ClassCastException with UDT

### ISSUE THREAD

**Issue by andreak** [impossibl/pgjdbc-ng#432]
This code worked with 0.7.1:
(It's Scala-code but you'll get the idea)
```scala
class BigIntVarcharJdbcData extends SQLData {

	var id: Long = 0
	var name: String = null
	var sqlType: String = null

	override def getSQLTypeName: String = {
		sqlType
	}

	override def writeSQL(stream: SQLOutput): Unit = {
		stream.writeLong(id)
		stream.writeString(name)
	}

	override def readSQL(stream: SQLInput, typeName: String): Unit = {
		sqlType = typeName
		id = stream.readLong()
		name = stream.readString()
	}
}
```
Then registered in a typemap:
```scala
object SQLUtils {
	val typeMap = {
		val h = new util.HashMap[String, Class[_]]()
		h.put("bigintvarchar", classOf[BigIntVarcharJdbcData])
		util.Collections.unmodifiableMap[String, Class[_]](h)
	}
}
```
and used like this:
```scala
rs.getObject("parent_activity_array", SQLUtils.typeMap).asInstanceOf[Array[BigIntVarcharJdbcData]]
```
With 0.9-SNAPSHOT I get this (package name of ```BigIntVarcharJdbcData``` stripped):
```
java.lang.ClassCastException: class com.impossibl.postgres.jdbc.PGBuffersArray cannot be cast to class [LBigIntVarcharJdbcData; (com.impossibl.postgres.jdbc.PGBuffersArray is in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @501286c3; [LBigIntVarcharJdbcData; is in unnamed module of loader org.apache.catalina.loader.WebappClassLoader @29d24657)
```
The returned type of that call is now:
![image](https://user-images.githubusercontent.com/321577/65744713-78392400-e0f9-11e9-80a9-44dd1bfd2bae.png)

Any hints?

**Comment by andreak** [comment]
Changing the call to
```Scala
rs.getObject("parent_activity_array", classOf[Array[BigIntVarcharJdbcData]])
```
works.
But shouldn't getObject passing a typeMap also work, as before?

**Comment by kdubb** [comment]
I think this is because 0.8 and above are _more_ JDBC compliant.  Previously when using `getObject` with arrays you'd get back an "array" with a specific element type... maybe. Now `getObject` returns the JDBC `java.sql.Array` as is mandated by JDBC.

Use something like this...
```java
java.sql.Array sqlArray = rs.getObject("array_col");
sqlArray.getArray(); // This is equivalent to what previous versions were returning
sqlArray.free(); // Don't forget to free the array!
```

**Comment by andreak** [comment]
Aha, so I first have to cast the return-value of getObject to java.sql.Array, then call getArray(), then free().
What about just passing the array-type directly, instead of the typemap, like my second post here?
Do I still have to free?

**Comment by kdubb** [comment]
The method you are demonstrated is essentially a `pgjdbc-ng` extension to JDBC. It's useful but has its limitations. For example, as you have discovered, you can't pass a type map and therefore all array items must be the same. When using this method there is no need to call `free` (nor is there a mechanism for you to do so).

While I don't foresee it being removed anytime soon, it is worth noting that getting a `java.sql.Array` and then calling `getArray` is the way the JDBC spec. is written and so portable code should be using that API.

**Comment by andreak** [comment]
I'd say ```rs.getObject("parent_activity_array", classOf[Array[BigIntVarcharJdbcData]])``` is _much_ cleaner, especially when you don't have to free() it. I'm _very_ tempted to just-do-it...

**Comment by andreak** [comment]
Anyway, I'll close this as it's a non-issue.
Thanks for the support:-)

**Comment by andreak** [comment]
Just curious; if free() is not called on an returend java.sql.Array (using pgjdbc-ng), will the resources get freed on TX-commit, or ResultSet.close? What are the consequences of not free()'ing?
