### ISSUE TITLE
blob.type=oid setting gone?

### ISSUE THREAD

**Issue by andreak** [impossibl/pgjdbc-ng#442]
In 0.7.1 version I had to set the parameter `blob.type=oid` in order for Blobs to work correctly agsinst PG's LO (OID).
I'm now getting this in the logs (0.8.3-SNAPSHOT pre-release)
```
WARNING: Applying unknown setting: blob.type
```

Is this setting not needed anymore to have "OID-blobs" work correctly?

**Comment by kdubb** [comment]
Yes! 🎉

0.8 delayed any type conversion until requested by JDBC, therefore any `oid` column can be requested as a `Blob` by simply calling `ResultSet.getBlob`.

**Comment by andreak** [comment]
Good!
