### ISSUE TITLE
getConnection in SQLData implementations

### ISSUE THREAD

**Issue by bartkaptur** [impossibl/pgjdbc-ng#445]
Hi,
I'm trying to translate a piece of code from an Oracle JDBC to PGJDBC-ng. Long story short: in Oracle, I was able to do this:

(...)
	public void writeSQL(SQLOutput stream) throws SQLException {
		OracleSQLOutput oracleStream = (OracleSQLOutput) stream;
		Connection currentConnection = oracleStream.getSTRUCT().getJavaSqlConnection();
(...)

I think it would be possible to add something similar to PGJDBC, by adding something like this to PGSQLOutput (I've seen it done like this in some other class):

    public PGConnection getConnection() {
        return (PGDirectConnection)this.context;
    }

Please tell me if I'm wrong - it seems to work fine, but maybe there are some circumstances I'm missing when it won't.

**Comment by kdubb** [comment]
No, that won't always work.  `Context` has a number of implementations/subclasses and get wrapped/unwrapped to alter some characteristics.

It seems you are trying to get the connection from an `SQLData` implementation... if I know the reason for that maybe there's a "more" JDBC way to solve it.

**Comment by kdubb** [comment]
I guess I should have read the title of the issue as well as the description 😂

**Comment by bartkaptur** [comment]
Thank you for a quick answer.
The reason: I have a structure, that I'm trying to pass to Postgres, that is basically an array (let's call it level 1) of objects with arrays (level 2) of their own.
I use connection.createArrayOf at both levels, and therefore I need an access to the connection.
The code is of a service kind, and therefore I can't put the connection (taken from a pool) in a global static variable.
I also can't add it as a local variable at level 2, as the objects at that level are re-created by jdbc, and all the data that's not in read/writeSQL is lost.
I can't see any other option except to make significant changes to the structure itself, and I'd like to avoid that.
If I'm missing something, please let me know.

**Comment by kdubb** [comment]
@bartkaptur Apologies that this got lost in my list.  Your usage is valid and it seems like we should be providing a `getConnection` method in `PGSQLOutput`.

**Comment by kdubb** [comment]
Added in 45b16e665413820c973a30ee3143ede627e5e3bd

**Comment by bartkaptur** [comment]
Great. Thank you.
