### ISSUE TITLE
Infinite wait closing connection when postgres server has been terminated

### ISSUE THREAD

**Issue by brettwooldridge** [impossibl/pgjdbc-ng#45]
When I shutdown my postgres server, and then try to close my application, the driver hangs trying to close connections.

Thread [Thread-2](Suspended)
    owns: ProtocolImpl  (id=122)
    owns: Object  (id=123)
    owns: ResourceLoader  (id=124)
    owns: BitronixTransactionManager  (id=125)
    waiting for: CloseCommandImpl$1  (id=126)
    Object.wait(long) line: not available [native method]
    CloseCommandImpl(CommandImpl).waitFor(ProtocolListener) line: 120
    CloseCommandImpl.execute(ProtocolImpl) line: 104
    ProtocolImpl.execute(Command) line: 365
    PGConnectionImpl.execute(Command, boolean) line: 364
    PGStatement.dispose(PGConnectionImpl, ServerObjectType, String) line: 184
    PGPreparedStatement(PGStatement).internalClose() line: 286
    PGPreparedStatement.internalClose() line: 148
    PGConnectionImpl.closeStatements(List<WeakReference<PGStatement>>) line: 312
    PGConnectionImpl.closeStatements() line: 329
    PGConnectionImpl.internalClose() line: 554
    PGConnectionImpl.close() line: 1107
    PGXAConnection(PGPooledConnection).close() line: 127
    JdbcPooledConnection.close() line: 157
    XAPool.close() line: 121
    PoolingDataSource.close() line: 349
    ResourceLoader.shutdown() line: 93
    BitronixTransactionManager.shutdown() line: 358
    Activator.stop(BundleContext) line: 124
    BundleContextImpl$2.run() line: 771
    AccessController.doPrivileged(PrivilegedExceptionAction<T>) line: not available [native method]
    BundleContextImpl.stop() line: 764
    BundleHost.stopWorker(int) line: 510
    BundleHost(AbstractBundle).stop(int) line: 465
    BundleHost(AbstractBundle).stop() line: 457
    CrateStarterElf.stopBundles(BundleContext, Crate...) line: 368
    ZApplication.stop() line: 237
    ZApplication$2.run() line: 330

**Comment by kdubb** [comment]
After 65f29228aa52d34f9a4dbad4edce12fb396b9aa4 this should report an SQLException
