### ISSUE TITLE
SQLException/ConversionException thrown with select datacl from pg_database

### ISSUE THREAD

**Issue by kwesterfeld** [impossibl/pgjdbc-ng#454]
If there are database permissions on a database that are granted to a role having the WITH GRANT OPTION, this is not parsable by the pgjdbc-ng driver (although it seems the 0.5 version worked).

The issue is that the acl item looks like this, and the regex in ACLItem.java does not allow for an asterisk:

```
yellowbrick=# select datname,datacl from pg_database;
        datname        |                                 datacl
-----------------------+------------------------------------------------------------------------
 template0             | {=c/kwesterfeld,kwesterfeld=CTc/kwesterfeld}
 _YBPG_stats           |
 template1             | {=c/kwesterfeld,kwesterfeld=CTc/kwesterfeld}
 yellowbrick           | {=Tc/kwesterfeld,kwesterfeld=CTc/kwesterfeld,ybd_test=CTc/kwesterfeld}
 yellowbrick_test      | {=Tc/yellowbrick,yellowbrick=CTc/yellowbrick,ybd_test=CTc/yellowbrick}
 yellowbrick_test_utf8 | {=Tc/yellowbrick,yellowbrick=CTc/yellowbrick,ybd_test=CTc/yellowbrick}
 moo                   | {kwesterfeld=CTc/kwesterfeld,foo=CTc*/kwesterfeld,too=T/kwesterfeld}
(7 rows)

```

NB: the "moo" database has the grant option where asterisk appears in the acl.

Stack trace: 

```
Caused by: java.sql.SQLException: com.impossibl.postgres.system.ConversionException: Unable to convert value to class com.impossibl.postgres.api.data.ACLItem
	at com.impossibl.postgres.jdbc.PGBuffersArray.getArray(PGBuffersArray.java:171)
	at com.impossibl.postgres.jdbc.PGArray.getArray(PGArray.java:91)
	at io.yellowbrick.smc.db.RowSet.processRow(RowSet.java:99)
	at io.yellowbrick.smc.db.impl.Table$1.processRow(Table.java:375)
	at org.springframework.jdbc.core.JdbcTemplate$RowCallbackHandlerResultSetExtractor.extractData(JdbcTemplate.java:1566)
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:693)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:629)
	... 88 more
Caused by: com.impossibl.postgres.system.ConversionException: Unable to convert value to class com.impossibl.postgres.api.data.ACLItem
	at com.impossibl.postgres.system.procs.AutoConvertingTextDecoder.decodeValue(BaseDecoders.java:292)
	at com.impossibl.postgres.system.procs.BaseTextDecoder.decode(BaseDecoders.java:218)
	at com.impossibl.postgres.system.procs.BaseTextDecoder.decode(BaseDecoders.java:196)
	at com.impossibl.postgres.jdbc.PGBuffersArray.getArray(PGBuffersArray.java:215)
	at com.impossibl.postgres.jdbc.PGBuffersArray.getArray(PGBuffersArray.java:168)
	... 94 more

```

**Comment by kdubb** [comment]
Adding in an allowance for an asterisk is easy but I'm not really understanding the extended format yet. Do you know what exactly the the asterisk means? Is it just "has with grant option"?

**Comment by kwesterfeld** [comment]
The asterisk means "WITH GRANT OPTION".

If you do something like:

```
% ybsql yellowbrick_test
ybsql (3.2.0)
Type:  \h for help with SQL commands
       \? for help with ybsql commands
       \g or terminate with semicolon to execute query
       \q to quit
yellowbrick_test=# create user kurt with login password 'kurt';
CREATE ROLE
yellowbrick_test=# create database foo;
CREATE DATABASE
yellowbrick_test=# grant connect on database foo to kurt with grant option;
GRANT
yellowbrick_test=# select datacl from pg_database;
                                 datacl
------------------------------------------------------------------------
 {=c/kwesterfeld,kwesterfeld=CTc/kwesterfeld}

 {=c/kwesterfeld,kwesterfeld=CTc/kwesterfeld}
 {=Tc/kwesterfeld,kwesterfeld=CTc/kwesterfeld,ybd_test=CTc/kwesterfeld}
 {=Tc/yellowbrick,yellowbrick=CTc/yellowbrick,ybd_test=CTc/yellowbrick}
 {=Tc/yellowbrick,yellowbrick=CTc/yellowbrick,ybd_test=CTc/yellowbrick}
 {=Tc/kwesterfeld,kwesterfeld=CTc/kwesterfeld,kurt=c*/kwesterfeld}
(7 rows)

yellowbrick_test=#
```

it will show up.

Note: our ybsql is a psql derivative for our product here at Yellowbrick
Data (which is derivative of Postgres)   In this example there is no
difference with stock PG.

**Comment by kdubb** [comment]
So would you suggest we surface it in `ACLItem` as something like `hasWithGrantOption`?

Forgive my naivete on all things role/grant related in PostgreSQL they are probably the features I've had least interaction with.

**Comment by kdubb** [comment]
When all else fails, read the source (https://github.com/postgres/postgres/blob/d40abd5fcfb25d764419f8e9bffa5cdbdb247c1b/src/backend/utils/adt/acl.c#L239).

~The `*` appears to mean all privileges preceding it are granted by the grant option and any following it are not~.

Upon further examination, the `*` signifies that the privilege preceding the star has the grant option; each privilege can have a star attached.

We need to alter `ACLItem` to surface this information...

Whereas currently `privileges` is a `String` of privilege codes, we would need to switch to something like:
```java
class ACLItem {
  static class Privilege {
    char code;
    boolean hasGrantOption;
  }
  String user;
  Privilege[] privileges
  String grantor;
}
```

alternatively we could just add an array of booleans that represent the grant options:
```java
class ACLItem {
  String user;
  String privileges
  boolean[] privilegeGrantOptions;
  String grantor;
}
```

Thoughts on which is the better solution?  The second has the advantage of being purely an addition to the public interface.

**Comment by kwesterfeld** [comment]
Actually that makes a lot of sense.   In our immediate usecase I “didn’t
care” and was just looking for the grant connect but this decorator may
help in the future build a better ux for our tools.

To do the workaround I casted to varchar, replace the *, and cast back to
acl[].

**Comment by kdubb** [comment]
#460 Fixes the parsing and adds new API for accessing the full scope of options for ACL items while keeping the old privileges string API for compatibility.
