### ISSUE TITLE
Support databaseName URL using URL encoding

### ISSUE THREAD

**Issue by kwesterfeld** [impossibl/pgjdbc-ng#455]
v0.8.3 of the driver supports percent-encoding (URL encoding) for parameters, username and password, but not database name.  Thus, creating a database with foo&bar or foo?bar or foo/bar is not possible, because the regex parser in ConnectionUtil becomes confused and cannot parse the database name.

It would be far better to support url encoding for the database name as well.

**Comment by kwesterfeld** [comment]
@kdubb is there a roadmap for when 0.8.4 with this fix will be released?

**Comment by kdubb** [comment]
No roadmap... but it will be end of this week unless some catastrophe interrupts me
