### ISSUE TITLE
Support unixsocket as a data source property

### ISSUE THREAD

**Issue by kwesterfeld** [impossibl/pgjdbc-ng#456]
Currently, the only way to specify the use of domain sockets for connecting to a database is through the JDBC URL mechanism using unixsocket=<socket>.   Because of this, the constraints of URL parsing are forced upon the configuration, and we end up with issues such as #455 where we have to encode the connection string but have limits on what we can place there.

Since we are using programmatic setup of the PGDataSource, it would be ideal to be able to specify the unixaddress to connect to via normal setUnixAddress and not have to bother with an URL connection property.

**Comment by kdubb** [comment]
Honestly I'm not quite sure why this isn't already the case.  It may just be an oversight but there's an outside chance it involves a technical issue because it does take a separate path.

**Comment by kdubb** [comment]
@kwesterfeld As you know PR's are welcome 😁

**Comment by kwesterfeld** [comment]
Thanks!

**Comment by kdubb** [comment]
#471 adds this and others.
