### ISSUE TITLE
DataSource.getConnection(user,password) clobbers settings

### ISSUE THREAD

**Issue by kwesterfeld** [impossibl/pgjdbc-ng#462]
We have a DataSource configured with a specific set of user settings and it is attached to a pool.  This pool, for all intents, is used to operate the application after login, with RBAC layered on top at the application level.   For login, this DataSource is also used to programmatically authenticate a user using the getConnection(user, password) entrypoint.  In previous versions of this driver, this did not leak said credentials into the DataSource, but more recent vintages of this driver do.  Specifically, the user and password passed to this method become stored in the DataSource, instead of layered with the DataSource settings.  I actually think this has got to be either a gap in the jdbc spec, or a bug in the spec that this behavior is not well-defined.  In any case, there are two main issues here, both security-related:
  1. Having the password of such a call clobber settings that were given for the DataSource earlier is bad form, morally wrong, incorrect, you-name-it.  I can't think of a case where this would be desirable.
 2.  It is not thread-safe.  Two simultaneous invocations of this entrypoint demonstrably clobber each other, leading to a security breach-in-wait.  I have actually seen this in practice where the password of one user was used to authenticate a different user account when two invocations of this method are called at the same time.

**Comment by kdubb** [comment]
To be clear, you are saying that every call to `DataSource.getConnection` sets the current value of the DataSource's user/password to whatever values was passed in?  If so, then yes that's a bug in the driver and not in the spec. (as far as I know).

**Comment by kdubb** [comment]
Verified via test. #463 fixes it.

This is a __big__ one. Good catch and thanks for reporting it. 👍
