### ISSUE TITLE
Add SCRAM-SHA-256 support

### ISSUE THREAD

**Issue by dfsilva** [impossibl/pgjdbc-ng#466]
Hey Guys,

Can you add support for SCRAM-SHA-256?

thanks

**Comment by bhemar** [comment]
Hi, do you have any plans to implement this? 

We want to use SCRAM-SHA-256 in our application, but the only solution is not to use pgjdbc-ng lib :(

**Comment by kdubb** [comment]
@bhemar #505 😉

**Comment by bhemar** [comment]
That's great news! Thnx for info
