### ISSUE TITLE
docker-compose tests: postgres service remains unhealthy

### ISSUE THREAD

**Issue by moio** [impossibl/pgjdbc-ng#475]
I see the following when running `./gradlew clean build`:

```
Waiting for postgres_1 to become healthy (it's unhealthy)
Waiting for postgres_1 to become healthy (it's unhealthy)
Waiting for postgres_1 to become healthy (it's unhealthy)
<=======------> 57% EXECUTING [15m 32s]
> :pgjdbc-ng:postgres12ComposeUp
```

After a long time it times out with the error:
```
  waiting for server to start....2020-02-07 08:28:49.539 UTC [33] FATAL:  private key file "/var/lib/postgresql/server.key" must be owned by the database user or root
  2020-02-07 08:28:49.539 UTC [33] LOG:  database system is shut down
   stopped waiting
```

I checked the key permissions and they are correct (0600, user invoking gradle).

What else can I check?

**Comment by kdubb** [comment]
Try using a different server version via the `postgresVersions` project property.  It accepts list of versions, so providing it a single version will only test that version. E.g. `./gradlew -PpostgresVersions=11 clean build`

**Comment by kdubb** [comment]
Also, PostgreSQL's SSL support is very pedantic about key file permissions and it want's the file to be owned by the `postgres` user _in docker_.

These are the permissions required...
```sh
chmod 0400 ./driver/src/test/resources/certdir/server/server.key
sudo chown 70:70 ./driver/src/test/resources/certdir/server/server.key
```

Note: This is regardless of what user uid 70 is on your host, uid 70 in the docker container is `postgres`, which is what it wants.

**Comment by moio** [comment]
> sudo chown 70:70 ./driver/src/test/resources/certdir/server/server.key

That's exactly what I needed. May I suggest to add that to the README, or even emit a warning from the build system when this condition is not met?

**Comment by kdubb** [comment]
Currently the build tries hard to detect this problem and emit a warning... 

https://github.com/impossibl/pgjdbc-ng/blob/02a9982950d431cd968bf8bd112ab631cfa039e6/driver/src/build/testing.gradle.kts#L145

**Comment by kdubb** [comment]
If you can determine why if, and why, it is not warning you we can update the check to detect your case as well.

**Comment by moio** [comment]
@kdubb I think the problem in my case was just the warning sentence:

https://github.com/impossibl/pgjdbc-ng/blob/02a9982950d431cd968bf8bd112ab631cfa039e6/driver/src/build/testing.gradle.kts#L156

In my case, the user running Gradle is `silvio`, UID 1000, while actually what we want is the file to be owned by UID 70, regardless what user is that (in fact, it might not be a valid user at all).

The warning was emitted correctly, but I was not able to figure out how to fix the situation (my mistake for not taking a glance to the code!)

**Comment by kdubb** [comment]
Update message in bcd081b8ff20233af41bced3473f81a8cda582d7
