### ISSUE TITLE
NullPointerException when reading Composite Types with null values

### ISSUE THREAD

**Issue by jsd64** [impossibl/pgjdbc-ng#479]
I use pgjdbc-ng 0.8.3 to access a PostgreSQL database which contains composite types. When trying to read a record which contains a composite type a NullPointerException is thrown when the composite type contains null values.

The exception occurs when calling the method getAttributes() of the class PGStruct.

Depending on the value type, the exception is thrown in different places:

Binary: BaseDecoders.java:74 in method BaseBinaryDecoder.decode() when calling the method checkArgument
String: Strings.java:194 in method BinDecoder.decodeNativeValue() when calling the method buffer.readableBytes()

**Comment by tlf30** [comment]
Have you tried using the 0.9 snapshots? Many fixes to UDTs are in 0.9

**Comment by kdubb** [comment]
@jsd64 I need more information. Can you provide a small repro test case so I can debug it?

**Comment by jsd64** [comment]
Sorry, it is difficult for me to provide a test case. My code is written in clojure and uses luminus for database integration. I identified two locations which throw an exception due to missing null-pointer checks, depending on the value type (binary or string).

If the value type is binary, the crash is in BaseDecoders.decode() (BaseDecoders.java:74):

      checkArgument(buffer.readableBytes() == requiredLength, "invalid length");

If the value type is string, the crash is in method Strings.decodeNativeValue (Strings.java:194):

      int length = buffer.readableBytes();

In both cases, buffer may be null.

I'm sorry I don't have more information.
