### ISSUE TITLE
How to handle JSON and JSONB data types?

### ISSUE THREAD

**Issue by ccleve** [impossibl/pgjdbc-ng#481]
After much googling, I haven't found the correct way to convert Postgres JSON and JSONB datatypes into Java objects. The official Postgres jdbc driver has PGobject, but I can't find the equivalent in pgjdbc-ng.

I'm using an ORM, so I'd really like to find a Java class that I can use in my pojos directly that will allow me to do selects and inserts without having to explicitly convert the json to and from a string.

What is the canonical way of handling json in pgjdbc-ng?

**Comment by kdubb** [comment]
JDBC currently has no support for a special "JSON" type.  So, JSON is handled as strings and should be received as such.

Just retrieve a string & parse it
```java
ResultSet rs = XXX;
String json = rs.getString("some_json");

// parse "json" it with your favorite JSON library
new ObjectMapper().readValue(json, MySpecialType.class);
```


`PGObject` from the mainstream driver is used to allow support for UDTs and other unsupported driver types by manually parsing the server response text. This driver instead supports complex UDTs and other types natively through JDBC's `Struct` and `SQLData` mechanisms. Not sure why you need `PGObject` for JSON.

Note that PostgreSQL _always_ sends & receives JSON (including JSONB) as normal UTF-8 encoded text stream so there is no performance penalty to just parsing the string you receive from the driver.
