### ISSUE TITLE
SSL wildcard certificates only work if hostname contains a '.' char

### ISSUE THREAD

**Issue by kwesterfeld2** [impossibl/pgjdbc-ng#482]
We are unable to connect to a database with SSLMode verify-full if the target database is configured using a wildcard certificate.

The offending code looks to be a stray ! in `driver/src/main/java/com/impossibl/postgres/protocol/v30/ServerConnectionFactory.java`:

```
      // We have a wildcard
      if (hostname.endsWith(CN.substring(1))) {
        // Avoid IndexOutOfBoundsException because hostname already ends with CN
        if (!(hostname.substring(0, hostname.length() - CN.length() + 1).contains("."))) {
          throw new SSLPeerUnverifiedException("The hostname " + hostname + " could not be verified");
        }
      }
```

By my read, if my target CN has *.company.com, and I am connecting to myhost.company.com, this throws "could not be verified".  If, however, I my target CN has *.company.com, and I am connecting to a host that contains a period (subdomain?), it works:   myhost.dev.company.com

**Comment by kdubb** [comment]
@kwesterfeld2 It's probably worth looking at #506, which alters this behavior _again_ to address SANs and proper wildcard matching. I'm in the process of adding tests to ensure it's correctness but it would be nice to know it still works in the wild.
