### ISSUE TITLE
Expose DETAIL-message in PGSQLIntegrityConstraintViolationException

### ISSUE THREAD

**Issue by andreak** [impossibl/pgjdbc-ng#485]
Hi, the following in log:
```
ERROR:  duplicate key value violates unique constraint "project_number_key"
DETAIL:  Key (project_number)=(216) already exists.
```
The `DETAIL`-message is not available in `PGSQLIntegrityConstraintViolationException`, it would be great if it would.
Any chance this DETAIL-message could be included?

**Comment by andreak** [comment]
I have code implementing this but unable to push a PR to this repo, how do I proceed?

**Comment by kdubb** [comment]
@andreak Github isn't letting you create a PR?

**Comment by andreak** [comment]
I try to create a PR from IDEA and when pushing I get:
Push failed Remote: Permission to impossibl/pgjdbc-ng.git denied to andreak. unable to access 'https://github.com/impossibl/pgjdbc-ng.git/': The requested URL returned error: 403

Do I have to fork the repo?

**Comment by andreak** [comment]
Here's a patch: https://visena.com/public/Implement_485.patch

**Comment by kdubb** [comment]
Yes you need to fork the repo into your private account and push to that; GitHub then offers to make a PR for you.
