### ISSUE TITLE
"null" in varchar-field is wrongly interpreted as null

### ISSUE THREAD

**Issue by andreak** [impossibl/pgjdbc-ng#493]
This test fails
```java
@RunWith(JUnit4.class)
public class StringNullTest {

  Connection conn;

  @Before
  public void before() throws Exception {
    conn = TestUtil.openDB();
    TestUtil.createTable(conn, "null_as_string_test", "val varchar");
  }

  @After
  public void after() throws SQLException {
    TestUtil.dropTable(conn, "null_as_string_test");
    TestUtil.closeDB(conn);
  }

  @Test
  public void testReadStringNull() throws Exception {

    PreparedStatement pst = conn.prepareStatement("INSERT INTO null_as_string_test(val) VALUES (?)");
    pst.setString(1, "null");
    pst.executeUpdate();
    pst.close();

    Statement st = conn.createStatement();
    ResultSet rs = st.executeQuery("SELECT val FROM null_as_string_test");
    assertTrue(rs.next());
    String value = rs.getString("val");
    assertNotNull(value); // Fails here
    assertEquals("should be \"null\"", "null", value);
  }

}
```

The driver should interpret 'null' in varchar-field as `"null"`, not `null`

**Comment by andreak** [comment]
To my surprise this is done on purpose here:
https://github.com/impossibl/pgjdbc-ng/blob/15cbf31602fd6ec080a25b51f5f3ad10a9de28f1/driver/src/main/java/com/impossibl/postgres/system/procs/BaseDecoders.java#L213-L215

Why? We actually have "null" as legitimate values comming from data-sources out of our control.

**Comment by kdubb** [comment]
Obviously this is a bug 😞.  I believe this stems from text protocol record parsing (where unquoted null means `null`) and not just a completely boneheaded mistake (hopefully).

**Comment by andreak** [comment]
Keep rocking!

**Comment by kdubb** [comment]
Please check #494 for sanity

**Comment by andreak** [comment]
My test-case passes, LGTM.

**Comment by kdubb** [comment]
I knew I was forgetting something, I meant to add your test case.

**Comment by andreak** [comment]
Btw; I'm not setting field.format - which, I think, implies using binary format. But it seems your fixes are for text-format, what's going on?

**Comment by kdubb** [comment]
It depends on your SQL query. For example,

```sql
SELECT 'null'; SELECT 1;
```

will always execute in text mode due to the backend protocol.  There are a number of other reasons it might return values in text format as well.

**Comment by andreak** [comment]
Ok
