### ISSUE TITLE
Release 0.8.5?

### ISSUE THREAD

**Issue by andreak** [impossibl/pgjdbc-ng#497]
With the recent (important) fixes in #494, are there any plans to spin a release?

**Comment by kdubb** [comment]
Going to try and tackle this in the coming week. I'm way behind 😔

**Comment by andreak** [comment]
:+1:

**Comment by andreak** [comment]
Ping:-)

**Comment by kdubb** [comment]
Done 🎉

**Comment by andreak** [comment]
Rock!
