### ISSUE TITLE
How do I build pgjdbc-ng-all?

### ISSUE THREAD

**Issue by andreak** [impossibl/pgjdbc-ng#500]
I'm not able to produce the pgjdbc-ng-all artifact.

I'm issuing:
```
./gradlew clean build -x test
```

But I only get the `pgjdbc-ng-<version>.jar`

Any hints?

**Comment by kdubb** [comment]
One way is to `./gradlew publishToMavenLocal` and grab it from your local repository. Alternatively, you can use
`./gradlew clean uberJar`, in this method the file will still be named without `-all` because that happens during publishing.

**Comment by andreak** [comment]
One step closer, but still failing:

```
$ ./gradlew clean publishToMavenLocal

> Configure project :pgjdbc-ng
DISABLING SSL, src/test/resources/certdir/server/server.key has invalid owner or permissions to execute PostgreSQL with SSL. Make sure it's owned by the user executing Gradle and its permissions are set to 0600

> Task :pgjdbc-ng:signShadowPublication FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pgjdbc-ng:signShadowPublication'.
> Cannot perform signing task ':pgjdbc-ng:signShadowPublication' because it has no configured signatory

```

Any hints on how to disable signing?

**Comment by andreak** [comment]
Got it, in `publishing.gradle.kts`
- Set isRelease=true
- Commented out the `configure<SigningExtension>` section

**Comment by kdubb** [comment]
Should be easier than that... 

```bash
$ ./gradlew clean publishToMavenLocal -Prelease=false
```

**Comment by andreak** [comment]
Ok, thanks!
