### ISSUE TITLE
Cleaning up leaked connection question 

### ISSUE THREAD

**Issue by dannyboyer** [impossibl/pgjdbc-ng#517]
Hi! I am implementing a spring-boot application that needs to LISTEN/NOTIFY forever to a postgres(12) db with pgjdbc-ng 0.8.6. After some time, I always stop receiving notifications once I get: 

`[WARN 22897 --- [PG-JDBC Housekeeper] c.i.postgres.jdbc.ThreadedHousekeeper    : Cleaning up leaked connection]`

I read the user guide and did not find something to prevent my connection from closing.
Is there something I can do to fix that?

I read somewhere that it is possible to disable the housekeeper, but wanted to make sure before doing that.
Thanks.

**Comment by miguelrvs** [comment]
Look for stale objects after GC runs.
Your Listener must be an object's field as your connection; if you are
creating your PGConnection or your NotificationListener as local variables,
when the GC passes they will gone because they were garbage collected.


Si quieres ser más positivo, pierde un electrón
Miguel Ruiz Velasco Sobrino

**Comment by kdubb** [comment]
FYI, the housekeeper only exists to "clean up" objects that weren't properly closed. This will only affect errant applications that do not follow the JDBC specification; which requires all connections, statements, result-sets, etc. to be explicitly closed. 

So, if your program is 100% compliant you do not need the housekeeper but at the same time it doesn't affect much leaving it enabled as it only tracks un-closed objects.

**Comment by dannyboyer** [comment]
@kdubb I don't understand how I could be 100% compliant as I need to keep my PGConnection open in order to receive notifications? Maybe I am missing something.

@miguelrvs I replaced my anonymous PGNotificationListener by a spring managed Bean that now hold the listener. Hopefully it won't get GCed.

**Comment by kdubb** [comment]
@dannyboyer Well if you _need_ to leave it open (as you do) then it's fine as long as you keep a reference to it.  The housekeeper only kicks in when you leak an object (i.e. you keep no more references to it but you didn't close it).

**Comment by dannyboyer** [comment]
In case anyone would be interested here is the resulting code

```
    public static void main(String[] args) {
        SpringApplication.run(ScannerApplication.class, args);
    }

    @Bean
    public JobProcessor jobProcessor() {
        return new JobProcessor(serverId);
    }

    @Bean
    public PGConnection pgConnection() throws SQLException {
        return DriverManager.getConnection(url, user, password).unwrap(PGConnection.class);
    }

    @Bean
    public PGNotificationListener listener(JobProcessor processor) {
        return new PGNotificationListener() {
            @Override
            public void notification(int processId, String channelName, String payload) {
                processor.process(payload);
            }

            @Override
            public void closed() {
                logger.error("PGConnection closed unexpectedly, you need to implement a reconnect mechanism");
            }
        };
    }

    @Override
    public void run(String... args) throws SQLException {
        final PGConnection connection = pgConnection();
        connection.addNotificationListener(listener(jobProcessor()));

        try (Statement statement = connection.createStatement()) {
            statement.executeUpdate("LISTEN new_job_channel");
        }
    }
```

**Comment by dannyboyer** [comment]
Thanks to @kdubb  and @miguelrvs the updated code works just fine without any leak!
