### ISSUE TITLE
Deadlock in ThreadedHousekeeper when closing connection

### ISSUE THREAD

**Issue by tlewowski** [impossibl/pgjdbc-ng#518]
My analysis (I don't know the codebase very well though, so I may be wrong somewhere):

When a connection is closed, `PGDirectConnection` closes `ThreadedHousekeeper`. In doing that, it locks `ThreadedHousekeeper` instance (`close` is `synchronized`) and waits for `cleanupThread` to complete (sending an interrupt earlier). This interrupt is usually dropped (`ThreadedHousekeeper.java:189-191`), and then `cleanupThread` proceeds to remove remaining reference from `cleanupReferences` collection. However, to do so, it has to lock `ThreadedHousekeeper.this` instance (`ThreadedHousekeeper:202`), which it cannot do, because it is already locked by `close` call.

So, Thread X calls `close` and waits for `cleanupThread` to complete (on `.join()`), but cleanup thread cannot complete, because it needs the lock kept by Thread X.

For me it happened on version 0.8.4, but from the code it seems that same can happen on 0.8.6.

I'll see if I can make a pull request with a fix, please confirm if you'd be interested

Stack traces from culprit threads: 
```

"PG-JDBC Housekeeper" #83415 daemon prio=10 os_prio=0 cpu=2109.95ms elapsed=31867.53s tid=0x00007f853c0a7000 nid=0x8fc9a waiting for monitor entry  [0x00007f84f18dd000]
 java.lang.Thread.State: BLOCKED (on object monitor)
      at com.impossibl.postgres.jdbc.ThreadedHousekeeper$1.run(ThreadedHousekeeper.java:202)
      - waiting to lock <0x000000008bc44320> (a com.impossibl.postgres.jdbc.ThreadedHousekeeper)
      
```
```
"DefaultDispatcher-worker-1" #83184 daemon prio=10 os_prio=0 cpu=302.65ms elapsed=32105.59s tid=0x00007f8534047800 nid=0x8fb26 in Object.wait()  [0x00007f84f0dd1000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@14.0.2/Native Method)
        - waiting on <no object reference available>
        at java.lang.Thread.join(java.base@14.0.2/Thread.java:1303)
        - locked <0x000000008bc00e78> (a com.impossibl.postgres.jdbc.ThreadedHousekeeper$1)
        at java.lang.Thread.join(java.base@14.0.2/Thread.java:1371)
        at com.impossibl.postgres.jdbc.ThreadedHousekeeper.close(ThreadedHousekeeper.java:269)
        - locked <0x000000008bc44320> (a com.impossibl.postgres.jdbc.ThreadedHousekeeper)
        at com.impossibl.postgres.jdbc.ThreadedHousekeeper.release(ThreadedHousekeeper.java:99)
        - locked <0x0000000080916be8> (a java.lang.Class for com.impossibl.postgres.jdbc.ThreadedHousekeeper)
        at com.impossibl.postgres.jdbc.ThreadedHousekeeper.access$000(ThreadedHousekeeper.java:49)
        at com.impossibl.postgres.jdbc.ThreadedHousekeeper$Ref.release(ThreadedHousekeeper.java:68)
        at com.impossibl.postgres.jdbc.PGDirectConnection.cleanupClosed(PGDirectConnection.java:696)
        at com.impossibl.postgres.jdbc.PGDirectConnection.internalClose(PGDirectConnection.java:685)
        at com.impossibl.postgres.jdbc.PGDirectConnection.close(PGDirectConnection.java:1367)
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcConnectionImpl.close(JdbcConnectionImpl.kt:36)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction.close(ThreadLocalTransactionManager.kt:85)
        at org.jetbrains.exposed.sql.Transaction.close(Transaction.kt)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:219)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:204)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:212)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:203)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:141)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:212)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:113)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:111)
```

**Comment by kdubb** [comment]
Good catch! 👏 And yes always interested... the *fix* _might_ be pretty obvious... 

The `cleanupThreadEnabled` is already an atomic boolean & `Thread.join()` is appears to not need the monitor (which wouldn't make much sense). So... just removing the `synchronized` from the  close method should stop the deadlock.

The larger question is that of ignoring `InterruptedException` in the housekeeper's thread.  The current code is clearly *wrong*, the close method calls `Thread.interrupt()` and the thread itself essentially ignores it.  _Should_ it try and interrupt the thread's cleanup duties? Probably not because all things should be cleaned up on close.

**Comment by kdubb** [comment]
We can honor the `Thread.interrupt()` request and still empty queue of immediately available references...
```java
    public void run() {

      while (cleanupThreadEnabled.get()) {

        HousekeeperReference<?> ref;
        try {
          ref = (HousekeeperReference<?>) cleanupQueue.remove();
        }
        catch (InterruptedException e1) {
          break;  // exit immediately and empty queue on exit
        }

        ref.clear();

        try {
          ref.cleanup();
        }
        catch (Throwable e) {
          // Ignore...
        }

        synchronized (ThreadedHousekeeper.this) {
          cleanupReferences.remove(ref);
        }
      }

      // Ensure immediately available references are cleaned up
      emptyQueue();
    }
```

**Comment by tlewowski** [comment]
I think that it wasn't exactly ignoring the interrupt - after one more read I think the point of the interrupt was to jump out of `cleanupQueue.remove()`, which I think is a blocking queue - so if we went with your proposal, we would also drop `ref.clear()`, `ref.cleanup()` and `cleanupReferences.remove(ref)` calls. 

But the same should happen now with `continue`. **Unless** the interrupt comes when the code is executing `ref.cleanup()`, which swallows all exceptions and continues to the `synchronized` block. Otherwise, the deadlock would happen each time when `ThreadedHousekeeper` is invoked. I think that `.cleanup()` usually doesn't block, but I don't think there are any guarantees for that. So perhaps that should be:

```
        try {
          ref.cleanup();
        }
        catch(InterrupedException ie) {
            break;
        }
        catch (Throwable e) {
          // Ignore...
        }

```

It's probably reasonable, since they'd be called on an obsolete `ref` anyway. One thing that bothers me a little is: what if the queue is not empty? Is dropping further cleanups OK, or should we do some cleaning anyway? Cleaning does things like printing stacks from leaking `ResultSet`s, so I see some value in them.

BTW, I think that `cleanupThreadEnabled` is not strictly necessary in current design. Since closing is already signalled by the interrupt, it'd be sufficient to simply do: 

```java

    public void run() {
      while (true) {
        HousekeeperReference<?> ref;
        try {
          ref = (HousekeeperReference<?>) cleanupQueue.remove();
        }
        catch (InterruptedException e1) {
          break;
        }

        ref.clear();

        try {
          ref.cleanup();
        }
        catch (Throwable e) {
          // Ignore...
        }

        synchronized (ThreadedHousekeeper.this) {
          cleanupReferences.remove(ref);
        }
      }
    }
```

Some flag would be needed if you'd want to run cleanups after the thread is interrupted, probably something like:

```java

    public void run() {
      boolean isDying = false;
      while (true) {
        HousekeeperReference<?> ref;
        try {
          ref = (HousekeeperReference<?>) (isDying ? cleanupQueue.poll() : cleanupQueue.remove());
          if(ref == null) {
            break;
          }
        }
        catch (InterruptedException e1) {
          isDying = true;
          continue;
        }

        ref.clear();

        try {
          ref.cleanup();
        }
        catch (Throwable e) {
          // Ignore...
        }

        synchronized (ThreadedHousekeeper.this) {
          cleanupReferences.remove(ref);
        }
      }
    }
```

I see you're doing that separately in `emptyQueue()`, but it's slightly different - it runs `ref.cleanup()`, but doesn't run `ref.clean()`, does that matter?

**Comment by kdubb** [comment]
> It's probably reasonable, since they'd be called on an obsolete ref anyway..

An "obsolete" ref isn't a thing... it'd be `null`, so there's nothing to do which is why I propose `break`ing out of the main loop.

> One thing that bothers me a little is: what if the queue is not empty?...

This is why I added a final (and un-interruptable) emptying of the queue via `emptyQueue`.

>  I see you're doing that separately in emptyQueue(), but it's slightly different...

`emptyQueue` should be calling `ref.clear()` as well 😉

**Comment by tlewowski** [comment]
right, because its scope is inside the loop, my bad. 

I'll post a PR for that soon

**Comment by kdubb** [comment]
Also, note that the Java spec. says an "interrupt" can happen for a number of reasons, not just our call to `Thread.interrupt()`.  This means the original method of calling `continue` is actually correct and the `cleanupThreadEnabled` field is still required.

Just need to un-syncrhonize the `close` method and add the `emptyQueue()` call after the thread has been disabled.

**Comment by tlewowski** [comment]
right, my bad. Probably I should read the spec more carefully 😉

**Comment by tlewowski** [comment]
and by the way, many thanks for immediate response!
