### ISSUE TITLE
Migration from v7.0 to 0.8.9: Issue with formatting binary data

### ISSUE THREAD

**Issue by hfazai** [impossibl/pgjdbc-ng#554]
I'm doing migration from pgjdbc-ng 7.0 to 0.8.9.

I'm storing a document as `bytea` and then I use jdom to parse it.

````JAVA
      byte[]      result = readByteFromTable();
      ByteArrayInputStream in = new ByteArrayInputStream(result);
      SAXBuilder        sxb = new SAXBuilder();

      document = sxb.build(in);
````

In 7.0 it works fine but in 0.8.9 it throws this exception in the line `document = sxb.build(in)` :
```
Caused by: com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence.
	at java.xml/com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.invalidByte(UTF8Reader.java:702)
	at java.xml/com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(UTF8Reader.java:568)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1904)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.skipSpaces(XMLEntityScanner.java:1638)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:818)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
```

I tried to read and print the same data using the two versions. Here is the different part:
- v7.0:
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration ...>...</configuration>
```
- v0.8.9:
```
<?xml version="1.0" encoding="UTF-8"?>�\�\<configuration ...>....</configuration>�\�\
```

It seems that it has a problem with formatting the new-line character.

**Comment by kdubb** [comment]
@hfazai Can you make a reproducer for this? It's hard to believe that the driver is doing anything with newlines as that code doesn't exist anywhere I know of.

**Comment by hfazai** [comment]
I quickly created a minimal example. Here is the code (in Kotlin):

````KOTLIN
const val DB_URL = "jdbc:pgsql://..."
const val DRIVER = "com.impossibl.postgres.jdbc.PGDriver"
const val USER = "..."
const val PASS = "..."
const val CREATE_QUERY = "CREATE TABLE IF NOT EXISTS test_table (bytes_col bytea NOT NULL)"
const val QUERY_INSERT = "INSERT INTO test_table (bytes_col) VALUES ('a\r\nb')"
const val QUERY_SELECT = "SELECT bytes_col FROM test_table"

fun main() {
  try {
    Class.forName(DRIVER);

    DriverManager.getConnection(DB_URL, USER, PASS).use { conn ->
      conn.createStatement().use { stmt ->
        stmt.execute(CREATE_QUERY)
        // Insert a value containing newline.
        stmt.executeUpdate(QUERY_INSERT)
        stmt.executeQuery(QUERY_SELECT).use { rs ->
          while (rs.next()) {
            // Display value as UTF-8 string
            val bytes  = rs.getBytes("bytes_col")
            println(bytes.toString(StandardCharsets.UTF_8))
          }
        }
      }
    }
  } catch (e: SQLException) {
    e.printStackTrace()
  }
}
````

### Output in V-0.7:
`a�\�\b`
### Output in V-0.8.9:
```
a
b
```

**Comment by kdubb** [comment]
Isn't the output of 0.8.9 what we want? You're calling `println` with a string containing a carriage-return and line-feed.

**Comment by kdubb** [comment]
```
Welcome to Kotlin version 1.4.10 (JRE 14+36-1461)
Type :help for help, :quit for quit
>>> println("a\r\nb")
a
b
```

**Comment by hfazai** [comment]
In fact the problem is that using the same database and the same code, I read the value differently.

We also store images that they changed after using the new version because the bytes are not the same.

**Comment by kdubb** [comment]
Can you try using a `PreparedStatement` with a string parameter?

**Comment by hfazai** [comment]
You mean to set column with bytes parameter?
````KOTLIN
const val QUERY_INSERT = "INSERT INTO test_table (bytes_col) VALUES (?)"
con.prepareStatement(QUERY_INSERT).use { stmt ->
        stmt.setBytes(1, "a\r\nb".toByteArray())
        stmt.executeUpdate()
}
````

Even with `PreparedStatement` When I read the inserted value I get `a�\�\b`

I think there is an issue with escape/hex format (https://www.postgresql.org/docs/9.5/datatype-binary.html)

**Comment by hfazai** [comment]
@kdubb I dont know if I made everything clear about this issue?

To make things more simple, If you store this bytearray `[97, 13, 10, 98]` and then try to read it you will get `[97, -67, 92, -70, 92, 98]`. you can repreduce it very easily using the code snippet above.

In my previous comments I gave the example with the string representation (`a\r\nb`) to help understanding and analysing the problem.

Please let me know if you need any other details.

**Comment by hfazai** [comment]
> Can you try using a `PreparedStatement` with a string parameter?

I think I misunderstood your suggestion! After using `PreparedStatement` to read the bytes I can get the same inserted value:

````KOTLIN
con.prepareStatement(QUERY_SELECT).use { stmt ->
  stmt.executeQuery().use { rs ->
    while (rs.next()) {
      val bytes = rs.getBytes("bytes_col")
      println(bytes.toString(StandardCharsets.UTF_8))
    }
  }
}
````

I didn't go very deep in inverstigation. But could you explain why should I use `PreparedStatement` in this case? Thanks in advance!

**Comment by hfazai** [comment]
@kdubb is this a bug or should I use `PreparedStatement` ? An explanation would be very appreciated.
