### ISSUE TITLE
Implement driver-side prepared statement cache

### ISSUE THREAD

**Issue by brettwooldridge** [impossibl/pgjdbc-ng#58]
Every major database vendor JDBC driver provides a prepared statement cache...except the classic PostgreSQL driver.  For example:

[MySQL](http://dev.mysql.com/doc/connector-j/en/connector-j-reference-configuration-properties.html)'s DataSource.  **Defaults to caching 25 statements.**

```
MysqlDataSource.setPrepStmtCacheSize()
```

[Oracle](http://docs.oracle.com/cd/B10500_01/java.920/a96654/stmtcach.htm) has both _implicit_ and _explicit_ caching (see link).

```
OracleDatasource.setMaxStatements();
```

[DB2](http://publib.boulder.ibm.com/infocenter/db2luw/v9r5/index.jsp?topic=%2Fcom.ibm.db2.luw.wn.doc%2Fdoc%2Fc0052011.html).

```
"maxStatements specifies the maximum number of statements that
 can be kept open by the driver in an internal statement cache"
```

[SQL Server](http://jtds.sourceforge.net/faq.html) via jTDS:

```
cacheMetaData (default - false)
```

As one of the authors of the relatively new [HikariCP](https://github.com/brettwooldridge/HikariCP) connection pool, we took the decision _not_ to implement statement caching in the pool because it is so widely implemented by JDBC drivers.  Not only does it add complexity to the pool, but JDBC drivers are actually in a better position to judge for a given database, given configuration, and given statement whether to cache or not cache.

In light of this, I think it would be great of pgjdbc-ng made up for the failings of "classic" PostgreSQL driver by offering prepared statement caching.

I am willing to implement, if pgjdbc-ng agrees in principal that it is useful.

**Comment by kdubb** [comment]
So that I am clear on understanding, please clarify how the statements would be cached.  I imagine you are talking about caching statements based on the SQL text itself?

**Comment by brettwooldridge** [comment]
Yes, I would envision caching the PGPreparedStatement instances based on the raw SQL text.  A "close" in this case would return the statement to the cache (an LRU cache).  If the connection is closed all statements in the LRU cache would be closed.  If adding a statement to the LRU pushes a statement out of the cache (capacity exceeded), the evicted statement would be closed.

I experimented locally with simple caching and reusing the SQLText instances so that SQLText.parse() was avoided.  I actually implemented the SQL parse tree cache many years ago in the jTDS (SQL Server) driver, and it is still in use there.  However, in pgjdbc-ng I quickly realized that the SQLText and it's contained hierarchy is not immutable as I thought it would be, but it's state is changed by the execution.  So, I modified the cache scheme to "parse once" then hand out copies of that SQLText, but in the end the deep-copy of the SQLText hierarchy provided little gain over the parse.  Though I _was_ using the cheap trick of Java serialization/deserialization to create a deep-copy, and Java serialization is notoriously slow.

Probably implementing a _custom_ deep-copy (not Java serialization) of the SQLText would actually perform quite well in comparison to a fresh parse, and may be worth the effort even if a prepared statement cache is used.  Caching the parsed SQLText can provide a speed-up not just a new statement preparation time, but also ad hoc execution via Statement.execute(String sql).

**Comment by jesperpedersen** [comment]
I agree that it would be nice to have a prepared statement cache in the driver itself.

However, I think we should look at optimizing the existing logic first, starting with the SQLText patch @brettwooldridge  has already. Then see what not using Java serialization could give. I think it is important to keep the code maintainable, so adding complexity for a small performance improvement needs to be carefully considered.

Lastly, I think any prepared statement cache internally in the driver should be off by default, since layers above may provide that functionality already - like Java EE environments. Furthermore there is issue of management and statistics of the cache too to consider.

**Comment by kdubb** [comment]
Thanks to @brettwooldridge we now have both a parsed sql cache and a prepared statement cache.  I'm closing this for now.
