### ISSUE TITLE
Does it support MATCH_RECOGNIZE?

### ISSUE THREAD

**Issue by fantasy0v0** [impossibl/pgjdbc-ng#580]
https://docs.oracle.com/database/121/JJDBC/apxref.htm#CHECHCJH

I often use the following code
```sql
select '{"foo": 1}'::jsonb ? 'foo';
```

This will give an error in PreparedStatement.

**Comment by kdubb** [comment]
PostgreSQL doesn't support it. This is a driver for PostgreSQL.

**Comment by fantasy0v0** [comment]
https://jdbc.postgresql.org/documentation/head/statement.html

**Comment by kdubb** [comment]
I'm not sure what you're referencing with that link? You asked about MATCH_RECOGNIZE which is an Oracle operator not supported by PostgreSQL. If you were asking using a `?`, then yes you can escape them with `??`.

**Comment by fantasy0v0** [comment]
> I'm not sure what you're referencing with that link? You asked about MATCH_RECOGNIZE which is an Oracle operator not supported by PostgreSQL. If you were asking using a `?`, then yes you can escape them with `??`.

sorry, I was looking for how to use ? in PreparedStatement before this.
when I looked at this link, I found that I asked a stupid question.
I'm just documenting how I solved it.
