### ISSUE TITLE
PreparedStatement performance issue

### ISSUE THREAD

**Issue by brettwooldridge** [impossibl/pgjdbc-ng#59]
While I was running some tests on the performance of PreparedStatements, I ran across a rather severe performance issue.

Comparing to the current PostgreSQL driver...

```
long start = System.nanoTime();
for (int i = 0; i < 100000; i++) {
    PreparedStatement prepareStatement = connection.prepareStatement("");
    prepareStatement.close();
}
System.out.println("Prepare: " + TimeUnit.NANOSECONDS.toMillis(System.nanoTime() - start));
```

With the current PostgreSQL driver this loop takes _198ms_ on my machine.  Using the pgjdbc-ng driver, the same loop takes _9872ms_.  Note this is with an _empty_ statement.

When I run the query (specific to my env):

``` sql
SELECT * from device WHERE hostname=? AND ip_low>0 AND ip_high<?
```

the performance for the PostgreSQL driver is _680ms_ and pgjdbc-ng is _11463ms_.  This is one order of magnitude difference.

**Comment by brettwooldridge** [comment]
When I run pgjdbc-ng under jProfile using sampling, I get this performance profile...

![screen shot 2014-01-20 at 3 13 24 pm](https://f.cloud.github.com/assets/1538661/1952040/16940a86-819a-11e3-9173-74fe436bf20e.png)

This indicates that the created `Cleanup` task is responsible for the majority of the overhead, followed closely by the regular expressions used in the `SQLText.parse()` code.

**Comment by kdubb** [comment]
This stems first and foremost from a principal difference between the 'classic' driver and 'ng'.  In 'ng' a prepared statement is just that, prepared on the server.  In 'classic' this doesn't happen.  Prepare it once and execute multiple times would be the proper way to do it in 'ng'.

The regex time is something to look at as running a regex (no matter how complicated) against an empty string should be nearly free.

**Comment by brettwooldridge** [comment]
Given that the `Cleanup` was showing up high, I tried disabling the housekeeper completely... this is the profile now:

![screen shot 2014-01-20 at 3 45 51 pm](https://f.cloud.github.com/assets/1538661/1952164/ce029a44-819e-11e3-8ce5-6735a68ba911.png)

The expensive part of `Cleanup` is creating the `Exception` here:

```
this.allocationStackTrace = new Exception().getStackTrace();
```

Turns out this is only used if `logLeaks` is `true`.  I made a local change that only captures the stack trace if `logLeaks` is `true`.  Unfortunately, there is no way to _disable_ logging leaks from the "outside", so I couldn't actually test it easily ... I just turned off the housekeeper for my test.  But it seems logging leaks should be optional (and `false` by default) with a setter on `PGDataSource`.

**Comment by brettwooldridge** [comment]
Just by not capturing the stack trace (turning off the housekeeper), and with the trivial change to `getNextStatementName()` (see pull request), the original test is down from _11463ms_ to _7868ms_.

**Comment by brettwooldridge** [comment]
"Prepare it once and execute multiple times would be the proper way to do it in 'ng'."

Just to add a little color to that statement.  While I understand that ideally that is the most efficient way to use a prepared statement, the reality is that ORM frameworks often prepare the same statement many thousands of times, assuming that the driver will "do the right thing".  Hibernate is one framework that does this a lot.  I am not currently a Hibernate user, but I have been in the past and ran into this behavior.  A few years back, I was working at a company that used Hibernate and SQL Server with the jTDS driver, and was actually the motivating factor to contribute SQL parse-tree caching to the jTDS project.  Obviously, the whole issue of prepare-time performance can be largely side-stepped with a prepared statement cache, but simple changes to the existing prepare code paths can also provide across the board speedups.

**Comment by jesperpedersen** [comment]
I would be ok with having the default value of 'housekeeper' be false.

**Comment by brettwooldridge** [comment]
I have some thoughts/questions jelling around the housekeeper.  This issue is largely resolved by the prepared statement cache, but I'd like to leave it open a bit longer...

**Comment by brettwooldridge** [comment]
I consider this issue closed with the merge from @kdubb.
