### ISSUE TITLE
Context unused in code?

### ISSUE THREAD

**Issue by brettwooldridge** [impossibl/pgjdbc-ng#63]
I found myself in `SQLTextEscapes.java` and the `Node processEscape(EscapeNode escape, Context context)` method...

In this method `context` is used in three places:

``` java
    switch(type.toString().toLowerCase()) {
      case "d":
        result = processDateEscape(escape, context);
        break;

      case "t":
        result = processTimeEscape(escape, context);
        break;

      case "ts":
        result = processTimestampEscape(escape, context);
...
```

However, looking into `processDateEscape()` et al, none of them use the `Context` that is passed in.  It seems like it was passed in because `Context` has these methods:

``` java
  DateTimeFormat getDateFormatter();
  DateTimeFormat getTimeFormatter();
  DateTimeFormat getTimestampFormatter();
```

However, they are not used.  Is this an oversight?  There are several call sites passing in `Context`, but if it is never used it is somewhat misleading as to its purpose.

**Comment by kdubb** [comment]
Context is really the connection and, well, you never know when you are going to need the connection!  So at some point I was probably using it and then maybe removed its usage.  Although I agree passing in useless parameters is not good practice, it's probably easier to leave it in than pull it out and then need it again some day.

**Comment by brettwooldridge** [comment]
Should we be using the formatters in `processDateEscape()` etc?

**Comment by kdubb** [comment]
It might be coming back to me as to why these are here... as it turns out Postgres always accepts ISO formatted dates.  So when sending text dates to the server I tend to just ISO format them (default of java.sql.Date) as it is just simpler.

**Comment by brettwooldridge** [comment]
I understand.
