### ISSUE TITLE
Question: Development Stalled

### ISSUE THREAD

**Issue by brettwooldridge** [impossibl/pgjdbc-ng#79]
Hi Kevin,

It seems that issues and pull requests are piling up as of late.  An engineer at my company also found issues with the XA support that we'd like to contribute fixes for.   You are somewhat familiar with my work through some earlier contributions.  If you wouldn't mind adding me as project contributor, I'll be happy to make what headway I can reviewing and integrating pull requests and fixing bugs.

**Comment by kdubb** [comment]
Agreed!  I've been swamped the last couple months and could use the help.

**Comment by kdubb** [comment]
@brettwooldridge @jesperpedersen 

Note that you both have been given read/write access.  The decision was easy based on your past contributions and demonstrated knowledge.

That being said.  Please ensure any large technological changes are well discussed between us before being committed ;)

**Comment by jesperpedersen** [comment]
@kdubb Thanks, and will do !
