### ISSUE TITLE
License under the Apache License

### ISSUE THREAD

**Issue by electrum** [impossibl/pgjdbc-ng#86]
This project looks very interesting. Would you consider licensing it under Apache License, Version 2.0 (ASL2)? https://www.apache.org/licenses/LICENSE-2.0

We have a basic JDBC driver in Presto (https://github.com/facebook/presto) and would be interested in collaborating here, but Presto is licensed under ASL2.

**Comment by niwinz** [comment]
BSD license is fully compatible with Apache License 2.0 as far as I known.
