### ISSUE TITLE
Query logging

### ISSUE THREAD

**Issue by volgar1x** [impossibl/pgjdbc-ng#94]
Hi,
You did a great job on pgjdbc-ng, but is there any query logging feature available ? I didn't find any information anywhere.

**Comment by kdubb** [comment]
Are you asking for an option to log all SQL text executed on the server?

**Comment by volgar1x** [comment]
That's effectively what I need

**Comment by kdubb** [comment]
Question.  Are you interested in seeing ALL the SQL submitted to the server, or just the SQL as a result of API usage.  In other words, the driver sometimes needs to execute SQL that you didn't explicitly ask for.  Do you care to filter that out? Just trying to figure out the best place to plug it in.

I guess we should have 2 options one for client generated SQL only and one for client & driver generated SQL.

**Comment by kdubb** [comment]
Implemented in #350.  Enable via `sql.trace=true` connection property or `pgjdbc.sql.trace=true` system property.
